
## Reject push notif [/customer/calls/reject]

### Reject push notif [POST]

Note:
1. BaseUrl : https://videokyc.ocbcnisp.com/verification/api/v2

+ Request (application/json)

        {
            "guid": "xxx-xxx-xxx-xxxx"
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {}
            }
        }
