
## Public Holiday List [/onfx/public-holiday-list]

### Public Holiday List [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUCCESS",
            "data": {
                "holidays": [
                    "20201224",
                    "20201224",
                    "20201225",
                    "20201225",
                    "20201225",
                    "20201224"
                ],
                "workingDay": true
            }
        }
