
## Init OTP [/token/register-customer-channel-request-otp]

### Init OTP [POST]

+ Request (application/json)

        {
            "category": "PINActivation",
            "phoneNumber": "08122183578"
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "uuid": "9EF852DF-BB31-4FB5-9F8F-0FD74DD93D40"
            }
        }
