
##  Product Detail SBN Retail [/primary-bonds/sbnretail/product/detail]

###  Product Detail SBN Retail [POST]

+ Request (application/json)

        {
            "secId": "205"
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "details" : [
                    {
                        "title":"Jenis Obligasi",
                        "value":"Government Bond",
                        "note": ""
                    },
                    {
                        "title":"Settlement Date",
                        "value":"30 January 2021",
                        "note": ""
                    },
                    {
                        "title":"Maturity Date",
                        "value":"30 January 2021",
                        "note": ""
                    },
                    {
                        "title":"Coupon Date",
                        "value":"10th of every month",
                        "note": ""
                    },
                    {
                        "title":"Coupon Rate",
                        "value":"5.70%",
                        "note": ""
                    },
                    {
                        "title":"Last Order Date",
                        "value":"30 January 2021, 10.00 WIB",
                        "note": ""
                    },
                    {
                        "title":"Sisa Kuota",
                        "value":"IDR 3.000.000,00",
                        "note": "informasi kuota diperoleh dari kementrian keuangan"
                    }
                ],
                "isEligibleToEarlyRedeem":true,
                "securityNo": "ORI SERI 16",
                "typeOfBond": "Government Bonds",
                "expireDate": "2021-03-16T00:00:00.000+0700",
                "settlementDate": "2021-03-16T00:00:00.000+0700",
                "maturityDate": "2021-03-16T00:00:00.000+0700",
                "listDetailRedemption" : [
                    {
                        "idSeri": 362,
                        "orderId": "33043",
                        "orderCode": "101T201911700013",
                        "nominalOrder": 1000000,
                        "nikSeller": "7777",
                        "nikReff": "0",
                        "trxBranch": "88539",
                        "insertedBy": "77777",
                        "minNominal": 1000000,
                        "maxNominal": 75000000,
                        "multiplesOfNominal": 1000000,
                        "orderDate": "2021-03-16T00:00:00.000+0700",
                        "isRedeemable": true,
                        "notRedeemableNote": "",
                        "sourceOfFund": {
                            "productCode": "TBSMCY9902",
                            "productName": "GIRO BUSINESS SMART",
                            "accountNo": "693810053779",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "accountId": "BD8078EF7538141AE053D407FF0A68AB",
                            "labelDebitAccount": "GIRO BUSINESS SMART 693800000723 IDR 65200583.00",
                            "cif": "0000000000001679512",
                            "accountBalances": [
                                {
                                    "accountCcy": "IDR",
                                    "balance": 693810053779,
                                    "isAvailable": true
                                }
                            ]
                        }
                    },
                    {
                        "idSeri": 362,
                        "orderId": "33044",
                        "orderCode": "101T201911700013",
                        "nominalOrder": 1000000,
                        "nikSeller": "7777",
                        "nikReff": "0",
                        "trxBranch": "88539",
                        "insertedBy": "77777",
                        "minNominal": 1000000,
                        "maxNominal": 75000000,
                        "multiplesOfNominal": 1000000,
                        "orderDate": "2021-03-16T00:00:00.000+0700",
                        "isRedeemable": false,
                        "notRedeemableNote": "This transaction can’t be redeemed now because it doesn’t reach IDR1,000,000,000.00",
                        "sourceOfFund": {
                            "productCode": "TBSMCY9902",
                            "productName": "GIRO BUSINESS SMART",
                            "accountNo": "693810053779",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "accountId": "BD8078EF7538141AE053D407FF0A68AB",
                            "labelDebitAccount": "GIRO BUSINESS SMART 693800000723 IDR 65200583.00",
                            "cif": "0000000000001679512",
                            "accountBalances": [
                                {
                                    "accountCcy": "IDR",
                                    "balance": 693810053779,
                                    "isAvailable": true
                                }
                            ]
                        }
                    }
                ]
            },
            "response_code": "00000"
        }
