
##  Early Redeem Confirmation SBN Retail [/primary-bonds/sbnretail/early-redeem/confirmation]

###  Early Redeem Confirmation SBN Retail [POST]

+ Request (application/json)

        {
            "idSeri": 362,
            "orderId": "33063",
            "orderCode": "101T201911700013",
            "nikSeller" : "77777",
            "nikReff" : "54393",
            "trxBranch": "88539",
            "insertedBy": "77777",
            "nominalRedemption" : 1000000.00
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "idSeri": 362,
                "orderId": "33063",
                "orderCode": "101T201911700013",
                "nikSeller" : "77777",
                "nikReff" : "54393",
                "trxBranch": "88539",
                "insertedBy": "77777",
                "nominalRedemption" : 1000000.00,
                "onlineSessionId": "693810053779--1000000-30ad6495-318e-4969-9850-e560b1ad3af0"
            },
            "response_code": "00000"
        }

