
## Retrieve Access Token [/oauth/token?grant_type=client_credentials]

### Retrieve Access Token [POST]

+ Response 200 (application/json)

        {
            "access_token": "bffc9bfb-7925-4f17-baa0-9e51cb93bf6b",
            "token_type": "bearer",
            "expires_in": 899,
            "scope": "read"
        }
