
## Ack QRIS Pay [/payment/ack-qris-pay]

### Ack QRIS Pay [POST]

+ Request (application/json)

        {
            "qrcode": "00020101021226690017ID.CO.DANAMON.WWW011893600011000000088802150000880800000200303UME27720020COM.BANKSINARMAS.WWW011893600153100290563402157338680866228710303UMI51320002000215ID10191010101180303UME52045812530336054100010001.005502015802ID5918AYAM GORENG SEKALI6010TANGGERANG61051511562070703C0163044A9F",
            "billAmount": 200000,
            "tipAmount": 10000,
            "totalAmount": 30000,
            "sourceAccount": {
                "productCode": "TBPAY10002",
                "productName": "TANDA PAYROLL 1-P",
                "accountNo": "693810003337",
                "accountType": "S",
                "branchCode": "99693",
                "mcBit": "N",
                "accountId": "AE28BF3D6C7CDA13E050A8C0940711A9",
                "labelDebitAccount": "TANDA PAYROLL 1-P 693810003337 IDR 2280351.00",
                "cif": "0000000000001679512",
                "accountBalances": [
                    {
                        "accountCcy": "IDR",
                        "balance": 2280351,
                        "isAvailable": true
                    }
                ]
            },
            "responseCodeOTP" : "626553",
            "onlineSessionId": "693810029464-693810029464-1001.00-6d0551a6-9927-413f-88de-40fb831c8e1c"
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "receipt": {
                    "transactionCode": "TRANSACTIONCODE",
                    "transactionId": "00dc7e54-f31b-40a1-a258-18b5ff06904a",
                    "sourceOfFund": {
                        "productName": "GIRO BUSINESS SMART",
                        "accountName": "ENDANG MUSTIKOWATI",
                        "productCode": "GRRMCY9902",
                        "accountNo": "693800000723",
                        "accountCcy": "IDR"
                    },
                    "listTransaction": [
                        {
                            "errorCode": "00000",
                            "errorDesc": "",
                            "recipients": {
                                "accountName": "Andi Budi",
                                "productName": "Token Listrik - R1M/900VA",
                                "accountNo": "08112345678"
                            },
                            "transactionCode": "TRANSACTIONCODE",
                            "transactionId": "00dc7e54-f31b-40a1-a258-18b5ff06904a",
                            "transactionStatus": "S",
                            "transactionAmount": 3250800.88,
                            "transactionCcy": "IDR",
                            "totalAmountDescription": "ekuivalen IDR 144010",
                            "transactionDate": "2020-08-25T16:55:32.000+00:00",
                            "headlines": [
                                {
                                    "title": "Token Listrik",
                                    "value": "1234 5678 9012 3456 1234"
                                }
                            ],
                            "descriptions": [
                                {
                                    "title": "",
                                    "value": "STRUK PEMBELIAN XL PAKET DATA"
                                },
                                {
                                    "title": "Pesan",
                                    "value": ""
                                },
                                {
                                    "title": "Metode Transfer",
                                    "value": "OCBC NISP"
                                },
                                {
                                    "title": "Waktu Transfer",
                                    "value": "Sekarang / Now"
                                },
                                {
                                    "title": "Reference Number",
                                    "value": "20200828101006"
                                }
                            ],
                            "footnote": "Informasi Hubungi Call Center 123 Atau Hubungi PLN Terdekat"
                        }
                    ]
                }
            }
        }
