
## Secondary Bonds Transaction Histories [/secondary-bonds/asset/histories]

### Secondary Bonds Transaction Histories [POST]

+ Request (application/json)

        {
            "accountNo" : "010810091867",
            "accountCcy" : "IDR",
            "page" : 1,
            "countPerPage" : 10
        }

+ Response 200 (application/json)

        {
            "response_code":"00000",
            "response_desc_en":"SUCCESS",
            "response_desc_id":"SUKSES",
            "data":{
                "resultCode":1000,
                "message":"Success",
                "data":[
                    {
                    "transactionDate":"2021-01-25T05:21:46.000+0000",
                    "valueDate":"11/09/2019",
                    "tranCode":"18",
                    "transDescription":"Pembelian Berhasil",
                    "trxDescription":"Harga 105.01",
                    "sign":"D",
                    "amount":50000000,
                    "balance":52505,
                    "remark1":null,
                    "remark2":null,
                    "remark3":null,
                    "remark4":null,
                    "chequeNo":null
                },
                {
                    "transactionDate":"2021-01-25T05:21:46.000+0000",
                    "valueDate":"11/09/2019",
                    "tranCode":"17",
                    "transDescription":"Pembelian Berhasil",
                    "trxDescription":"Harga 105.01",
                    "sign":"D",
                    "amount":102000000,
                    "balance":100000000,
                    "remark1":null,
                    "remark2":null,
                    "remark3":null,
                    "remark4":null,
                    "chequeNo":null
                },
                {
                    "transactionDate":"2021-01-24T05:21:46.000+0000",
                    "valueDate":"11/09/2019",
                    "tranCode":"16",
                    "transDescription":"Pembelian Berhasil",
                    "trxDescription":"Harga 105.01",
                    "sign":"D",
                    "amount":50000000,
                    "balance":52505,
                    "remark1":null,
                    "remark2":null,
                    "remark3":null,
                    "remark4":null,
                    "chequeNo":null
                },
                {
                    "transactionDate":"2021-01-24T05:21:46.000+0000",
                    "valueDate":"11/09/2019",
                    "tranCode":"15",
                    "transDescription":"Pembelian Berhasil",
                    "trxDescription":"Harga 105.01",
                    "sign":"D",
                    "amount":102000000,
                    "balance":100000000,
                    "remark1":null,
                    "remark2":null,
                    "remark3":null,
                    "remark4":null,
                    "chequeNo":null
                },
                {
                    "transactionDate":"2021-01-24T05:21:46.000+0000",
                    "valueDate":"11/09/2019",
                    "tranCode":"14",
                    "transDescription":"Pembelian Berhasil",
                    "trxDescription":"Harga 105.01",
                    "sign":"D",
                    "amount":50000000,
                    "balance":52505,
                    "remark1":null,
                    "remark2":null,
                    "remark3":null,
                    "remark4":null,
                    "chequeNo":null
                },
                {
                    "transactionDate":"2021-01-23T05:21:46.000+0000",
                    "valueDate":"11/09/2019",
                    "tranCode":"13",
                    "transDescription":"Pembelian Berhasil",
                    "trxDescription":"Harga 105.01",
                    "sign":"D",
                    "amount":102000000,
                    "balance":100000000,
                    "remark1":null,
                    "remark2":null,
                    "remark3":null,
                    "remark4":null,
                    "chequeNo":null
                },
                {
                    "transactionDate":"2021-01-23T05:21:46.000+0000",
                    "valueDate":"11/09/2019",
                    "tranCode":"12",
                    "transDescription":"Pembelian Berhasil",
                    "trxDescription":"Harga 105.01",
                    "sign":"D",
                    "amount":50000000,
                    "balance":52505,
                    "remark1":null,
                    "remark2":null,
                    "remark3":null,
                    "remark4":null,
                    "chequeNo":null
                },
                {
                    "transactionDate":"2021-01-23T05:21:46.000+0000",
                    "valueDate":"11/09/2019",
                    "tranCode":"11",
                    "transDescription":"Pembelian Berhasil",
                    "trxDescription":"Harga 105.01",
                    "sign":"D",
                    "amount":102000000,
                    "balance":100000000,
                    "remark1":null,
                    "remark2":null,
                    "remark3":null,
                    "remark4":null,
                    "chequeNo":null
                },
                {
                    "transactionDate":"2021-01-23T05:21:46.000+0000",
                    "valueDate":"11/09/2019",
                    "tranCode":"10",
                    "transDescription":"Pembelian Berhasil",
                    "trxDescription":"Harga 105.01",
                    "sign":"D",
                    "amount":50000000,
                    "balance":52505,
                    "remark1":null,
                    "remark2":null,
                    "remark3":null,
                    "remark4":null,
                    "chequeNo":null
                }
            ],
            "page": 1,
            "countPerPage": 10,
            "totalAllData": 9
            }
        }
        