
## Buy Secondary bonds Unit [/secondary-bonds/buy/unit]

### Buy Secondary bonds Unit [POST]

Error Codes
1. B0093 - Stock Tidak Tersedia

+ Request (application/json)
        
        {
            "productCode": "206",
            "amount": 50000000
        }

+ Response 200 (application/json)
        

        {
            "responseDescription": "SUKSES", 
            "responseTitle": "",
            "language": "IN",
            "data": {},
            "response_code": "00000"
        }
        