
## Buy Secondary bonds Apply [/secondary-bonds/buy/apply]

### Buy bonds Apply [POST]

Error Codes
1. B0091 - Mata Uang Tidak tersedia
2. B0092 - Cut Off Buy

+ Request (application/json)
        
        {
            "productCurrency": "IDR",
            "startTime": "08:00",
            "endTime": "17:00"
        }

+ Response 200 (application/json)
        

        {
            "responseDescription": "SUKSES", 
            "responseTitle": "",
            "language": "IN",
            "data": {},
            "response_code": "00000"
        }
        