
## Secondary bonds Product Detail [/secondary-bonds/product/detail]

### Secondary bonds Product Detail [POST]

+ Request (application/json)
        
        {
            "productCode":"206"
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "response_code": "00000",
            "data": {
                "cifId": "1234",
                "securityNo": "SR 56",
                "productAccountNo": "12",
                "productCode": "206",
                "productName": "FR 61",
                "productDescription": "INDON ONE MOBILE",
                "productCurrency": "IDR",
                "productCategory": "Obligasi Pemerintah",
                "productRiskProfile": "Menengah-Tinggi",
                "yearPerformancePercent" : 6.55486,
                "couponRate" : 6.55486,
                "faceValue": 150000000,
                "maturityDate": "2021-03-16T17:00:00.000+00:00",
                "settlementDate": "2021-03-16T17:00:00.000+00:00",
                "suitabilityBit": false,
                "navAmount": 105.91000,
                "navDate": "2021-03-16T17:00:00.000+00:00",
                "tax": 15.00000,
                "capitalPrice": 80000,
                "minNominal": 1000000,
                "maxNominal": 75000000,
                "multiplesOfNominal": 1000000,
                "listPerformance": [
                    {
                        "performType": "1D",
                        "performTitle": "Daily",
                        "percentage": 0
                    },
                    {
                        "performType": "1W",
                        "performTitle": "Weekly",
                        "percentage": 23.94
                    },
                    {
                        "performType": "1M",
                        "performTitle": "Monthly",
                        "percentage": -17.62
                    },
                    {
                        "performType": "1Y",
                        "performTitle": "Yearly",
                        "percentage": -5.25
                    }
                ],
                "urlDocument": "https://www.ocbcnisp.com/-/media/feature/pdf/adhoc/fitur-produk/fr.pdf",
                "startTime": "08:00",
                "endTime": "17:00"
            }
        }
        