
## Secondary Bonds Product Inquiry [/secondary-bonds/product/inquiry]

### Secondary Bonds Product Inquiry [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "riskProfileNasabah":"B",
                "riskProfileNasabahDesc":"Aggressive",
                "lastUpdateRiskProfile":"2021-01-25T05:21:46.000+0000",
                "categories": [
                    "Obligasi Pemerintah",
                    "Obligasi Korporasi"
                ],
                "products": [
                    {
                        "productCode": "206",
                        "productName": "FR 61",
                        "productCcy": "IDR",
                        "productCategory": "Obligasi Pemerintah",
                        "productRiskProfile" : "Menengah-Tinggi",
                        "yearPerformancePercent" : 6.55486,
                        "suitabilityBit": true,
                        "urlIconMI": "https://cdn3.iconfinder.com/data/icons/diagram_v2/PNG/96x96/diagram_v2-27.png",
                        "navAmount" : 115.75000
                    },
                    {
                        "productCode": "205",
                        "productName": "ORI SERI 002",
                        "productCcy": "IDR",
                        "productCategory": "Obligasi Korporasi",
                        "productRiskProfile" : "Menengah-Tinggi",
                        "yearPerformancePercent" : -6.55486,
                        "suitabilityBit": false,
                        "urlIconMI": "https://cdn3.iconfinder.com/data/icons/diagram_v2/PNG/96x96/diagram_v2-27.png",
                        "navAmount" : 120.75000
                    }
                ]
            },
            "response_code": "00000" 
        }
