
## Block Card [/card/block_card]

### Block Card [POST]

+ Request (application/json)

        {
            "pan":"123456",
            "source_system": "818301283929"
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES"
        }
