
## Change source of fund online debit Card [/card/vdc/change-source-of-funds]


### Change source of fund online debit Card [POST]

+ Request (application/json)

        {
            "instrPAN" : "5183169085916428",
            "instrChunk" : "2ed0f980a5",
            "accountNo" : "693810021354",
            "accountType" : "S",
            "productCode" : "TBSMCY9901"
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "response_code": "00000"
        }
