
## Get rsa key for pin cc encryption [/card/credit/key]


### Get rsa key for pin cc encryption [GET]

+ Request (application/json)

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "rsaPublicKeyParsed": {
                        "modulus": "7mskbOrgzq63QSPozMC/UQCFNVS1dyO7TYph90GvJXLTz9iielqNMaF7ax72iRQRhzVfR+nnaZ1+sCC3jnOzCFx0i3I3djBhtLdhHTM11EPmvrxMVB2CP74SIBk57BshspvzvGIHVNXQWwzSfp1+tQjXkfeL6PnjBFt79DRfG18=",
                        "exponent": "AQAB"
                    }
            },
            "response_code": "00000"
        }
