
## List Debit Card [/card/list_debit_card]

### List Debit Card [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "errorCode": "000",
                "errorDesc": "SUCCESS",
                "listOfCard": [
                    {
                        "accountNumber": "999888777001",
                        "sourceSystem": "way4",
                        "cvv2": null,
                        "cvv2CHUNK": null,
                        "chunk": null,
                        "contract_NUMBER": null,
                        "base_RELATION": null,
                        "rbs_NUMBER": null,
                        "ecom_AMOUNT": null,
                        "recr_AMOUNT": null,
                        "tds_PH_NUMBER": null,
                        "tr_FIRST_NAM": null,
                        "tr_LAST_NAM": null,
                        "company_NAME": null,
                        "card_EXPIRE": null,
                        "contract_NAME": null,
                        "reg": null,
                        "productCodeIssuing": null,
                        "productCodeRelated": null,
                        "issuingCard_CONTRACTNUMBER": null,
                        "card_STATUS_NUM": null,
                        "ecom_USAGE_REC_DATE": null,
                        "productCodePrimary": null,
                        "recr_USAGE_REC_DATE": null,
                        "cif": null,
                        "cardImage": null,
                        "cardName": "LOCAL BIN",
                        "pan": "6034399060000398",
                        "cardColours": [
                            "#f14545",
                            "#c41431"
                        ],
                        "cardStatus": "BLOCKED",
                        "paymentNetwork": "UNKNOWN",
                        "cardType": "GPN"
                    },
                    {
                        "accountNumber": "760810000173",
                        "sourceSystem": "way4",
                        "cvv2": null,
                        "cvv2CHUNK": null,
                        "chunk": null,
                        "contract_NUMBER": null,
                        "base_RELATION": null,
                        "rbs_NUMBER": null,
                        "ecom_AMOUNT": null,
                        "recr_AMOUNT": null,
                        "tds_PH_NUMBER": null,
                        "tr_FIRST_NAM": null,
                        "tr_LAST_NAM": null,
                        "company_NAME": null,
                        "card_EXPIRE": null,
                        "contract_NAME": null,
                        "reg": null,
                        "productCodeIssuing": null,
                        "productCodeRelated": null,
                        "issuingCard_CONTRACTNUMBER": null,
                        "card_STATUS_NUM": null,
                        "ecom_USAGE_REC_DATE": null,
                        "productCodePrimary": null,
                        "recr_USAGE_REC_DATE": null,
                        "cif": null,
                        "cardImage": null,
                        "cardName": "DEFAULT",
                        "pan": "9360002810000000124",
                        "cardColours": [
                            "#f14545",
                            "#c41431"
                        ],
                        "cardStatus": "ACTIVE",
                        "paymentNetwork": "UNKNOWN",
                        "cardType": "MASTERCARD"
                    }
                ]
            }
        }
