
## List Credit Card [/card/list_credit_card]

### List Credit Card [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "listOfCard": [
                    {
                        "productCode": "MCTNM1",
                        "productName": "MASTERCARD TITANIUM UMUM",
                        "accountCcy": "IDR",
                        "balance": 672653,
                        "availableBalance": 49835681,
                        "holdBalance": 50000000,
                        "overdraftBalance": 0,
                        "maturityDate": "2020-09-21T10:00:00.000+00:00",
                        "estimatedAmount": 672653,
                        "accountType": "C",
                        "ccHolderType": "S",
                        "accountId": "B28CD205771FD7B7E050A8C094071ACD",
                        "ccNumber": "5241691100001035",
                        "cif": "0000000000000737237",
                        "cardType": "MASTERCARD",
                        "cardColours": [
                            "#002976",
                            "#0060e6"
                        ]
                    },
                    {
                        "productCode": "MCTNM1",
                        "productName": "MASTERCARD TITANIUM UMUM",
                        "accountCcy": "IDR",
                        "balance": 672653,
                        "availableBalance": 49835681,
                        "holdBalance": 50000000,
                        "overdraftBalance": 0,
                        "maturityDate": "2020-09-21T10:00:00.000+00:00",
                        "estimatedAmount": 672653,
                        "accountType": "C",
                        "ccHolderType": "S",
                        "accountId": "B28CD2057721D7B7E050A8C094071ACD",
                        "ccNumber": "5241691100001340",
                        "cif": "0000000000000737237",
                        "cardType": "MASTERCARD",
                        "cardColours": [
                            "#002976",
                            "#0060e6"
                        ]
                    },
                    {
                        "productCode": "MCTNM1",
                        "productName": "MASTERCARD TITANIUM UMUM",
                        "accountCcy": "IDR",
                        "balance": 672653,
                        "availableBalance": 49835681,
                        "holdBalance": 50000000,
                        "overdraftBalance": 672653,
                        "maturityDate": "2020-09-21T10:00:00.000+00:00",
                        "estimatedAmount": 672653,
                        "accountType": "C",
                        "ccHolderType": "P",
                        "accountId": "B28CD2057724D7B7E050A8C094071ACD",
                        "ccNumber": "5241691100001027",
                        "cif": "0000000000000737237",
                        "cardType": "MASTERCARD",
                        "cardColours": [
                            "#002976",
                            "#0060e6"
                        ]
                    },
                    {
                        "productCode": "VISPL1",
                        "productName": "VISA LIQUID PLATINUM",
                        "accountCcy": "IDR",
                        "balance": 14534375,
                        "availableBalance": 10000000,
                        "holdBalance": 10000000,
                        "overdraftBalance": 0,
                        "maturityDate": "2020-09-21T10:00:00.000+00:00",
                        "estimatedAmount": 14534375,
                        "accountType": "C",
                        "ccHolderType": "S",
                        "accountId": "B28CD2057722D7B7E050A8C094071ACD",
                        "ccNumber": "4645831100003293",
                        "cif": "0000000000000737237",
                        "cardType": "VISA",
                        "cardColours": [
                            "#cdcdcd",
                            "#939793"
                        ]
                    },
                    {
                        "productCode": "VISPL1",
                        "productName": "VISA LIQUID PLATINUM",
                        "accountCcy": "IDR",
                        "balance": 14534375,
                        "availableBalance": 95330049,
                        "holdBalance": 100000000,
                        "overdraftBalance": 14534375,
                        "maturityDate": "2020-09-21T10:00:00.000+00:00",
                        "estimatedAmount": 14534375,
                        "accountType": "C",
                        "ccHolderType": "P",
                        "accountId": "B28CD2057723D7B7E050A8C094071ACD",
                        "ccNumber": "4645831100003301",
                        "cif": "0000000000000737237",
                        "cardType": "VISA",
                        "cardColours": [
                            "#cdcdcd",
                            "#939793"
                        ]
                    },
                    {
                        "productCode": "VISPL1",
                        "productName": "VISA LIQUID PLATINUM",
                        "accountCcy": "IDR",
                        "balance": 14534375,
                        "availableBalance": 10000000,
                        "holdBalance": 10000000,
                        "overdraftBalance": 0,
                        "maturityDate": "2020-09-21T10:00:00.000+00:00",
                        "estimatedAmount": 14534375,
                        "accountType": "C",
                        "ccHolderType": "S",
                        "accountId": "B28CD2057720D7B7E050A8C094071ACD",
                        "ccNumber": "4645831100002543",
                        "cif": "0000000000000737237",
                        "cardType": "VISA",
                        "cardColours": [
                            "#cdcdcd",
                            "#939793"
                        ]
                    }
                ]
            }
        }
