
## List Parameter online debit Card [/card/vdc/list_parameter]


### List Parameter online debit Card [GET]

+ Request (application/json)

        

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "getParameterResult": {
                    "maxFreeCard": 3,
                    "maxCard": 5,
                    "chargeCard": 30000,
                    "chargeCustomPAN": 50000,
                    "cardPrefix": "518316"
                },
                "cardResult": {
                    "cardColours": [
                        "#c41432",
                        "#710013"
                    ]
                }
            },
            "response_code": "00000"
        }
