
## List Online Debit Card [/card/list_virtual_debit_card]

### List Online Debit Card [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "listOfCard": [
                    {
                        "accountNumber": null,
                        "sourceSystem": null,
                        "cvv2": "32132b3-cdf9-4d425",
                        "cvv2CHUNK": "58bb52f880fd453e",
                        "chunk": "a5a9ed4fd4",
                        "contract_NUMBER": "5183169085916428",
                        "base_RELATION": "110",
                        "rbs_NUMBER": "076130001095",
                        "ecom_AMOUNT": "1000000",
                        "recr_AMOUNT": "1000000",
                        "tds_PH_NUMBER": "081220011636",
                        "tr_FIRST_NAM": "NAME2",
                        "tr_LAST_NAM": "760003944257",
                        "company_NAME": null,
                        "card_EXPIRE": "2203",
                        "contract_NAME": "NAME2 760003944257",
                        "reg": "678990",
                        "productCodeIssuing": "CRD_MCVDC_C-I",
                        "productCodeRelated": "CRD_MCVDC_C-R",
                        "issuingCard_CONTRACTNUMBER": "028-CARD_ISS-190535640",
                        "card_STATUS_NUM": "14",
                        "ecom_USAGE_REC_DATE": "2018-11-02 10:39:00",
                        "productCodePrimary": "CRD_MCVDC_C-P",
                        "recr_USAGE_REC_DATE": "2018-11-02 10:39:00",
                        "cif": "0000000760003944257",
                        "paymentNetwork": null,
                        "cardType": "MASTERCARD",
                        "cardColours": [
                            "#c41432",
                            "#710013"
                        ],
                        "pan": null,
                        "cardName": "MASTERCARD VIRTUAL DEBIT",
                        "cardStatus": "Card OK",
                        "cardImage": null
                    },
                    {
                        "accountNumber": null,
                        "sourceSystem": null,
                        "cvv2": "c3c61ff-495d-4f137",
                        "cvv2CHUNK": "cf102a4367174bb5",
                        "chunk": "9f1316efa5",
                        "contract_NUMBER": "5183169337661137",
                        "base_RELATION": "110",
                        "rbs_NUMBER": "076130001095",
                        "ecom_AMOUNT": "1000000",
                        "recr_AMOUNT": "1000000",
                        "tds_PH_NUMBER": "081220011636",
                        "tr_FIRST_NAM": "NAME2",
                        "tr_LAST_NAM": "760003944257",
                        "company_NAME": null,
                        "card_EXPIRE": "2203",
                        "contract_NAME": "NAME2 760003944257",
                        "reg": "678790",
                        "productCodeIssuing": "CRD_MCVDC_C-I",
                        "productCodeRelated": "CRD_MCVDC_C-R",
                        "issuingCard_CONTRACTNUMBER": "028-CARD_ISS-215710110",
                        "card_STATUS_NUM": "14",
                        "ecom_USAGE_REC_DATE": "2018-11-02 10:39:00",
                        "productCodePrimary": "CRD_MCVDC_C-P",
                        "recr_USAGE_REC_DATE": "2018-11-02 10:39:00",
                        "cif": "0000000760003944257",
                        "paymentNetwork": null,
                        "cardType": "MASTERCARD",
                        "cardColours": [
                            "#c41432",
                            "#710013"
                        ],
                        "pan": null,
                        "cardName": "MASTERCARD VIRTUAL DEBIT",
                        "cardStatus": "Card OK",
                        "cardImage": null
                    },
                    {
                        "accountNumber": null,
                        "sourceSystem": null,
                        "cvv2": "9b3c208-40ca-46684",
                        "cvv2CHUNK": "2ef4d7fc05a94143",
                        "chunk": "63831bca9d",
                        "contract_NUMBER": "5183166342410062",
                        "base_RELATION": "110",
                        "rbs_NUMBER": "076130001095",
                        "ecom_AMOUNT": "1000000",
                        "recr_AMOUNT": "1000000",
                        "tds_PH_NUMBER": "081221007791",
                        "tr_FIRST_NAM": "RAPHAELISTY",
                        "tr_LAST_NAM": "BENIGNOM",
                        "company_NAME": null,
                        "card_EXPIRE": "2005",
                        "contract_NAME": "NAME2 760003944257",
                        "reg": "487910",
                        "productCodeIssuing": "CRD_MCVDC_C-I",
                        "productCodeRelated": "CRD_MCVDC_C-R",
                        "issuingCard_CONTRACTNUMBER": "028-CARD_ISS-916185010",
                        "card_STATUS_NUM": "14",
                        "ecom_USAGE_REC_DATE": "2018-11-02 10:39:00",
                        "productCodePrimary": "CRD_MCVDC_C-P",
                        "recr_USAGE_REC_DATE": "2018-11-02 10:39:00",
                        "cif": "0000000760003944257",
                        "paymentNetwork": null,
                        "cardType": "MASTERCARD",
                        "cardColours": [
                            "#c41432",
                            "#710013"
                        ],
                        "pan": null,
                        "cardName": "MASTERCARD VIRTUAL DEBIT",
                        "cardStatus": "Card OK",
                        "cardImage": null
                    }
                ]
            },
            "response_code": "00000"
        }
