
## Bank List [/fundtransfer/list_bank_code]

### Bank List [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "listBank": [
                    {
                        "bankId": "028",
                        "bankName": "OCBC NISP",
                        "availableTransaction": [
                            "IFT"
                        ]
                    },
                    {
                        "bankId": "061",
                        "bankName": "ANZ",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "531",
                        "bankName": "BANK AMAR INDONESIA",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "037",
                        "bankName": "BANK ARTHA GRAHA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "040",
                        "bankName": "BANK BANGKOK",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "137",
                        "bankName": "BANK BANTEN",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "014",
                        "bankName": "BANK BCA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "536",
                        "bankName": "BANK BCA SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "133",
                        "bankName": "BANK BENGKULU",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "459",
                        "bankName": "BANK BISNIS INTERNATIONAL",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "110",
                        "bankName": "BANK BJB",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "425",
                        "bankName": "BANK BJB SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "009",
                        "bankName": "BANK BNI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "427",
                        "bankName": "BANK BNI SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "057",
                        "bankName": "BANK BNP PARIBAS",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "688",
                        "bankName": "BANK BPR KS",
                        "availableTransaction": [
                            "OLT"
                        ]
                    },
                    {
                        "bankId": "002",
                        "bankName": "BANK BRI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "494",
                        "bankName": "BANK BRI AGRONIAGA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "422",
                        "bankName": "BANK BRI SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "200",
                        "bankName": "BANK BTN",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "200",
                        "bankName": "BANK BTN SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "213",
                        "bankName": "BANK BTPN",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "547",
                        "bankName": "BANK BTPN SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "441",
                        "bankName": "BANK BUKOPIN",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "521",
                        "bankName": "BANK BUKOPIN SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "076",
                        "bankName": "BANK BUMI ARTA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "054",
                        "bankName": "BANK CAPITAL",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "949",
                        "bankName": "BANK CHINATRUST",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "022",
                        "bankName": "BANK CIMB NIAGA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "022",
                        "bankName": "BANK CIMB NIAGA SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "950",
                        "bankName": "BANK COMMONWEALTH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "011",
                        "bankName": "BANK DANAMON",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "011",
                        "bankName": "BANK DANAMON SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "046",
                        "bankName": "BANK DBS",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "067",
                        "bankName": "BANK DEUTSCHE",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "501",
                        "bankName": "BANK DIGITAL BCA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "111",
                        "bankName": "BANK DKI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "111",
                        "bankName": "BANK DKI SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "699",
                        "bankName": "BANK EKA",
                        "availableTransaction": [
                            "OLT"
                        ]
                    },
                    {
                        "bankId": "562",
                        "bankName": "BANK FAMA INTERNATIONAL",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "161",
                        "bankName": "BANK GANESHA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "567",
                        "bankName": "BANK HARDA INTERNASIONAL",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "164",
                        "bankName": "BANK ICBC",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "513",
                        "bankName": "BANK INA PERDANA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "555",
                        "bankName": "BANK INDEX",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "542",
                        "bankName": "BANK JAGO",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "472",
                        "bankName": "BANK JASA JAKARTA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "113",
                        "bankName": "BANK JATENG",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "113",
                        "bankName": "BANK JATENG SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "114",
                        "bankName": "BANK JATIM",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "114",
                        "bankName": "BANK JATIM SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "095",
                        "bankName": "BANK JTRUST INDONESIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "123",
                        "bankName": "BANK KALBAR",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "123",
                        "bankName": "BANK KALBAR SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "125",
                        "bankName": "BANK KALTENG",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "484",
                        "bankName": "BANK KEB HANA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "535",
                        "bankName": "BANK KESEJAHTERAAN EKONOMI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "008",
                        "bankName": "BANK MANDIRI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "451",
                        "bankName": "BANK MANDIRI SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "564",
                        "bankName": "BANK MANDIRI TASPEN",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "548",
                        "bankName": "BANK MAS",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "157",
                        "bankName": "BANK MASPION INDONESIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "097",
                        "bankName": "BANK MAYAPADA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "016",
                        "bankName": "BANK MAYBANK",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "016",
                        "bankName": "BANK MAYBANK SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "553",
                        "bankName": "BANK MAYORA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "426",
                        "bankName": "BANK MEGA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "506",
                        "bankName": "BANK MEGA SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "151",
                        "bankName": "BANK MESTIKA DHARMA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "048",
                        "bankName": "BANK MIZUHO",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "485",
                        "bankName": "BANK MNC INTERNASIONAL",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "147",
                        "bankName": "BANK MUAMALAT",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "118",
                        "bankName": "BANK NAGARI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "118",
                        "bankName": "BANK NAGARI SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "947",
                        "bankName": "BANK NET INDONESIA SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "503",
                        "bankName": "BANK NOBU",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "033",
                        "bankName": "BANK OF AMERICA",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "069",
                        "bankName": "BANK OF CHINA (HKG)",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "146",
                        "bankName": "BANK OF INDIA INDONESIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "042",
                        "bankName": "BANK OF TOKYO MITSUBISHI UFJ",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "526",
                        "bankName": "BANK OKE",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "019",
                        "bankName": "BANK PANIN",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "517",
                        "bankName": "BANK PANIN SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "013",
                        "bankName": "BANK PERMATA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "013",
                        "bankName": "BANK PERMATA SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "167",
                        "bankName": "BANK QNB INDONESIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "089",
                        "bankName": "BANK RABOBANK",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "047",
                        "bankName": "BANK RESONA PERDANIA",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "523",
                        "bankName": "BANK SAHABAT SAMPOERNA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "498",
                        "bankName": "BANK SBI INDONESIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "152",
                        "bankName": "BANK SHINHAN INDONESIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "153",
                        "bankName": "BANK SINARMAS",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "153",
                        "bankName": "BANK SINARMAS SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "120",
                        "bankName": "BANK SUMSEL BABEL",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "120",
                        "bankName": "BANK SUMSEL BABEL SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "023",
                        "bankName": "BANK UOB",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "566",
                        "bankName": "BANK VICTORIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "405",
                        "bankName": "BANK VICTORIA SYARIAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "212",
                        "bankName": "BANK WOORI SAUDARA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "490",
                        "bankName": "BANK YUDHA BHAKTI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "129",
                        "bankName": "BPD BALI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "112",
                        "bankName": "BPD DIY",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "112",
                        "bankName": "BPD DIY SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "116",
                        "bankName": "BPD ISTIMEWA ACEH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "115",
                        "bankName": "BPD JAMBI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "122",
                        "bankName": "BPD KALSEL",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "122",
                        "bankName": "BPD KALSEL SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "124",
                        "bankName": "BPD KALTIM KALTARA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "124",
                        "bankName": "BPD KALTIM KALTARA SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "121",
                        "bankName": "BPD LAMPUNG",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "131",
                        "bankName": "BPD MALUKU",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "128",
                        "bankName": "BPD NTBS",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "130",
                        "bankName": "BPD NTT",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "132",
                        "bankName": "BPD PAPUA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "119",
                        "bankName": "BPD RIAU KEPRI",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "126",
                        "bankName": "BPD SULAWESI SELATAN",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "134",
                        "bankName": "BPD SULAWESI TENGAH",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "135",
                        "bankName": "BPD SULAWESI TENGGARA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "127",
                        "bankName": "BPD SULAWESI UTARA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "117",
                        "bankName": "BPD SUMUT",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "117",
                        "bankName": "BPD SUMUT SYARIAH",
                        "availableTransaction": [
                            "RTGS-S",
                            "LLG-S"
                        ]
                    },
                    {
                        "bankId": "028475",
                        "bankName": "BPR DANAGUNG ABADI",
                        "availableTransaction": [
                            "OLT"
                        ]
                    },
                    {
                        "bankId": "028474",
                        "bankName": "BPR DANAGUNG BAKTI",
                        "availableTransaction": [
                            "OLT"
                        ]
                    },
                    {
                        "bankId": "028473",
                        "bankName": "BPR DANAGUNG RAMULTI",
                        "availableTransaction": [
                            "OLT"
                        ]
                    },
                    {
                        "bankId": "600",
                        "bankName": "BPR/LSB",
                        "availableTransaction": [
                            "OLT"
                        ]
                    },
                    {
                        "bankId": "036",
                        "bankName": "CHINA CONSTRUCTION BANK INDONESIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "031",
                        "bankName": "CITIBANK",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "087",
                        "bankName": "HSBC INDONESIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "032",
                        "bankName": "JPMORGAN CHASE BANK",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "911",
                        "bankName": "LINKAJA",
                        "availableTransaction": [
                            "OLT"
                        ]
                    },
                    {
                        "bankId": "789",
                        "bankName": "PAYPRO",
                        "availableTransaction": [
                            "OLT"
                        ]
                    },
                    {
                        "bankId": "520",
                        "bankName": "PRIMA MASTER BANK",
                        "availableTransaction": [
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "945",
                        "bankName": "PT. BANK IBK INDONESIA",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    },
                    {
                        "bankId": "050",
                        "bankName": "STANDARD CHARTERED",
                        "availableTransaction": [
                            "OLT",
                            "RTGS-C",
                            "LLG-C"
                        ]
                    }
                ]
            }
        }
