
## Transfer Method List [/fundtransfer/channels]

### Transfer Method [POST]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "metodeTransfers": [
                    {
                        "channel": "OLT",
                        "fee": 6500,
                        "minAmount": 10000,
                        "maxAmount": 50000000,
                        "startHour": "18:00",
                        "endHour": "23:50",
                        "description": "Transfer di hari yang sama",
                        "rangeAmount": "Nilai transaksi IDR 10.000,00 - 50.000.000,00",
                        "trcFee": "Biaya transaksi IDR 6.500,00",
                        "opTime": "Tersedia pada 18:00 - 23:50 (hari kerja)",
                        "enabled": true,
                        "additionalInfoFlag": false
                    },
                    {
                        "channel": "RTGS",
                        "fee": 2000,
                        "minAmount": 100000000,
                        "maxAmount": 1000000000,
                        "startHour": "08:00",
                        "endHour": "23:50",
                        "description": "Transfer di hari yang sama",
                        "rangeAmount": "Nilai transaksi IDR 100.000.000,00 - 1.000.000.000,00",
                        "trcFee": "Biaya transaksi IDR 2.000,00",
                        "opTime": "Tersedia pada 08:00 - 23:50 (hari kerja)",
                        "enabled": true,
                        "additionalInfoFlag": true
                    },
                    {
                        "channel": "LLG",
                        "fee": 2000,
                        "minAmount": 10000,
                        "maxAmount": 1000000000,
                        "startHour": "02:00",
                        "endHour": "22:50",
                        "description": "Transfer di hari yang sama",
                        "rangeAmount": "Nilai transaksi IDR 10.000,00 - 1.000.000.000,00",
                        "trcFee": "Biaya transaksi IDR 2.000,00",
                        "opTime": "Tersedia pada 02:00 - 22:50 (hari kerja)",
                        "enabled": true,
                        "additionalInfoFlag": true
                    }
                ]
            }
        }
