## Fetch City Parameter [/parameter/city]

### Fetch City Parameter [POST]

+ Request (application/json)

        {
            "provinceCode" : "RIAU"
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "parameters": [
                    {
                        "code": "Batam, Kota",
                        "value": "Batam, Kota",
                        "description": ""
                    },
                    {
                        "code": "Bengkalis, Kab.",
                        "value": "Bengkalis, Kab.",
                        "description": ""
                    },
                    {
                        "code": "Bintan, Kab (d/h Kab. Kepulauan Riau)",
                        "value": "Bintan, Kab (d/h Kab. Kepulauan Riau)",
                        "description": ""
                    },
                    {
                        "code": "Dumai, Kota.",
                        "value": "Dumai, Kota.",
                        "description": ""
                    },
                    {
                        "code": "Indragiri Hilir, Kab.",
                        "value": "Indragiri Hilir, Kab.",
                        "description": ""
                    },
                    {
                        "code": "Indragiri Hulu, Kab.",
                        "value": "Indragiri Hulu, Kab.",
                        "description": ""
                    },
                    {
                        "code": "Kampar, Kab.",
                        "value": "Kampar, Kab.",
                        "description": ""
                    },
                    {
                        "code": "Kuantan Singingi, Kab.",
                        "value": "Kuantan Singingi, Kab.",
                        "description": ""
                    },
                    {
                        "code": "Pekanbaru, Kota.",
                        "value": "Pekanbaru, Kota.",
                        "description": ""
                    },
                    {
                        "code": "Pelalawan, Kab.",
                        "value": "Pelalawan, Kab.",
                        "description": ""
                    },
                    {
                        "code": "Rokan Hilir, Kab.",
                        "value": "Rokan Hilir, Kab.",
                        "description": ""
                    },
                    {
                        "code": "Rokan Hulu, Kab.",
                        "value": "Rokan Hulu, Kab.",
                        "description": ""
                    },
                    {
                        "code": "Siak, Kab.",
                        "value": "Siak, Kab.",
                        "description": ""
                    }
                ]
            },
            "response_code": "00000"
        }
