
## Fetch Currencies without Priority [/parameter/currencies-without-priority]

### Fetch Currencies without Priority [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "currencies": [
                    {
                        "accountCcy": "USD",
                        "accountCcyNameID": "Dolar Amerika",
                        "accountCcyNameEN": "US Dollar"
                    },
                    {
                        "accountCcy": "SGD",
                        "accountCcyNameID": "Dolar Singapura",
                        "accountCcyNameEN": "Singapore Dollar"
                    },
                    {
                        "accountCcy": "EUR",
                        "accountCcyNameID": "Euro",
                        "accountCcyNameEN": "Euro"
                    },
                    {
                        "accountCcy": "GBP",
                        "accountCcyNameID": "Poundsterling",
                        "accountCcyNameEN": "British Pound"
                    },
                    {
                        "accountCcy": "AUD",
                        "accountCcyNameID": "Dolar Australia",
                        "accountCcyNameEN": "Australian Dollar"
                    },
                    {
                        "accountCcy": "NZD",
                        "accountCcyNameID": "Dolar Selandia Baru",
                        "accountCcyNameEN": "New Zealand Dollar"
                    },
                    {
                        "accountCcy": "JPY",
                        "accountCcyNameID": "Yen Jepang",
                        "accountCcyNameEN": "Japanese Yen"
                    },
                    {
                        "accountCcy": "HKD",
                        "accountCcyNameID": "Dolar Hongkong",
                        "accountCcyNameEN": "Hong Kong Dollar"
                    },
                    {
                        "accountCcy": "CHF",
                        "accountCcyNameID": "Franc Swiss",
                        "accountCcyNameEN": "Swiss Franc"
                    },
                    {
                        "accountCcy": "CAD",
                        "accountCcyNameID": "Dolar Kanada",
                        "accountCcyNameEN": "Canadian Dollar"
                    },
                    {
                        "accountCcy": "CNH",
                        "accountCcyNameID": "China Yuan Off",
                        "accountCcyNameEN": "Chinese Yuan Off"
                    }
                ]
            }
        }
