## Fetch District Parameter [/parameter/district]

### Fetch District Parameter [POST]

+ Request (application/json)

        {
            "provinceCode" : "RIAU",
            "cityCode" : "Indragiri Hulu, Kab."
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "parameters": [
                    {
                        "code": "BATANG CENAKU",
                        "value": "BATANG CENAKU",
                        "description": ""
                    },
                    {
                        "code": "BATANG GANSAI",
                        "value": "BATANG GANSAI",
                        "description": ""
                    },
                    {
                        "code": "KELAYANG",
                        "value": "KELAYANG",
                        "description": ""
                    },
                    {
                        "code": "KUALA CENAKU",
                        "value": "KUALA CENAKU",
                        "description": ""
                    },
                    {
                        "code": "Kuantan Hilir",
                        "value": "Kuantan Hilir",
                        "description": ""
                    },
                    {
                        "code": "Kuantan Mudik",
                        "value": "Kuantan Mudik",
                        "description": ""
                    },
                    {
                        "code": "Kuantan Tengah",
                        "value": "Kuantan Tengah",
                        "description": ""
                    },
                    {
                        "code": "LIRIK",
                        "value": "LIRIK",
                        "description": ""
                    },
                    {
                        "code": "LUBUK BATU JAYA",
                        "value": "LUBUK BATU JAYA",
                        "description": ""
                    },
                    {
                        "code": "PASIR PENYU",
                        "value": "PASIR PENYU",
                        "description": ""
                    },
                    {
                        "code": "PERANAP",
                        "value": "PERANAP",
                        "description": ""
                    },
                    {
                        "code": "RAKIT KULIM",
                        "value": "RAKIT KULIM",
                        "description": ""
                    },
                    {
                        "code": "RENGAT",
                        "value": "RENGAT",
                        "description": ""
                    },
                    {
                        "code": "RENGAT BARAT",
                        "value": "RENGAT BARAT",
                        "description": ""
                    },
                    {
                        "code": "RENGAT LAINNYA",
                        "value": "RENGAT LAINNYA",
                        "description": ""
                    },
                    {
                        "code": "SEBERIDA",
                        "value": "SEBERIDA",
                        "description": ""
                    },
                    {
                        "code": "SIBERIDA",
                        "value": "SIBERIDA",
                        "description": ""
                    },
                    {
                        "code": "Singingi",
                        "value": "Singingi",
                        "description": ""
                    }
                ]
            },
            "response_code": "00000"
        }
