
## ITR Parameter Source Of Fund [/parameter/itr/source-of-fund]

### ITR Parameter Source Of Fund [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "sourceOfFunds" : [
                    {
                        "accountNo" : "06081012345568",
                        "productName" : "GIRO MULTICURRENCY",
                        "details" : [
                            {
                                "code": "06081012345568|IDR",
                                "value" : "06081012345568 (IDR)",
                                "description" : ""
                            },
                            {
                                "code": "06081012345568|USD",
                                "value": "06081012345568 (USD)",
                                "description" : ""
                            },
                            {
                                "code": "06081012345568|SGD",
                                "value": "06081012345568 (SGD)",
                                "description" : ""
                            }
                        ]
                    },
                    {
                        "accountNo" :  "09081012345568",
                        "productName" : "TANDA MULTICURRENCY",
                        "details" : [
                            {
                                "code": "09081012345568|IDR",
                                "value": "09081012345568 (IDR)",
                                "description" : ""
                            },
                            {
                                "code": "09081012345568|USD",
                                "value": "09081012345568 (USD)",
                                "description" : ""
                            },
                            {
                                "code": "09081012345568|SGD",
                                "value": "09081012345568 (SGD)",
                                "description" : ""
                            }
                        ]
                    },
                    {
                        "accountNo" :  "09081054232132",
                        "productName" : "TANDA MULTICURRENCY",
                        "details" : [
                            {
                                "code": "09081054232132|IDR",
                                "value": "09081054232132 (IDR)",
                                "description" : ""
                            },
                            {
                                "code": "09081054232132|USD",
                                "value": "09081054232132 (USD)",
                                "description" : ""
                            },
                            {
                                "code": "09081054232132|SGD",
                                "value": "09081054232132 (SGD)",
                                "description" : ""
                            }
                        ]
                    }
                ]
            },
            "response_code": "00000"
        }