
## Fetch ONFX Currencies [/parameter/onfx-currencies]

### Fetch ONFX Currencies [POST]

+ Request (application/json)

        {
            "currencies": ["USD", "AUD", "SGD"]
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "currencies": [
                    {
                        "accountCcy": "USD",
                        "accountCcyNameID": "Dolar US",
                        "accountCcyNameEN": "US Dollar"
                    },
                    {
                        "accountCcy": "AUD",
                        "accountCcyNameID": "Dolar Australia",
                        "accountCcyNameEN": "Australian Dollar"
                    },
                    {
                        "accountCcy": "SGD",
                        "accountCcyNameID": "Dolar Singapura",
                        "accountCcyNameEN": "Singapore Dollar"
                    }
                ]
            }
        }
