## Fetch Province Parameter [/parameter/province]

### Fetch Province Parameter [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "parameters": [
                    {
                        "code": "ACEH",
                        "value": "ACEH",
                        "description": ""
                    },
                    {
                        "code": "BALI",
                        "value": "BALI",
                        "description": ""
                    },
                    {
                        "code": "BANTEN",
                        "value": "BANTEN",
                        "description": ""
                    },
                    {
                        "code": "BENGKULU",
                        "value": "BENGKULU",
                        "description": ""
                    },
                    {
                        "code": "DI YOGYAKARTA",
                        "value": "DI YOGYAKARTA",
                        "description": ""
                    },
                    {
                        "code": "DKI JAKARTA",
                        "value": "DKI JAKARTA",
                        "description": ""
                    },
                    {
                        "code": "GORONTALO",
                        "value": "GORONTALO",
                        "description": ""
                    },
                    {
                        "code": "JAMBI",
                        "value": "JAMBI",
                        "description": ""
                    },
                    {
                        "code": "JAWA BARAT",
                        "value": "JAWA BARAT",
                        "description": ""
                    },
                    {
                        "code": "JAWA TENGAH",
                        "value": "JAWA TENGAH",
                        "description": ""
                    },
                    {
                        "code": "JAWA TIMUR",
                        "value": "JAWA TIMUR",
                        "description": ""
                    },
                    {
                        "code": "KALIMANTAN BARAT",
                        "value": "KALIMANTAN BARAT",
                        "description": ""
                    },
                    {
                        "code": "KALIMANTAN SELATAN",
                        "value": "KALIMANTAN SELATAN",
                        "description": ""
                    },
                    {
                        "code": "KALIMANTAN TENGAH",
                        "value": "KALIMANTAN TENGAH",
                        "description": ""
                    },
                    {
                        "code": "KALIMANTAN TIMUR",
                        "value": "KALIMANTAN TIMUR",
                        "description": ""
                    },
                    {
                        "code": "KALIMANTAN UTARA",
                        "value": "KALIMANTAN UTARA",
                        "description": ""
                    },
                    {
                        "code": "KEPULAUAN BANGKA BELITUNG",
                        "value": "KEPULAUAN BANGKA BELITUNG",
                        "description": ""
                    },
                    {
                        "code": "KEPULAUAN RIAU",
                        "value": "KEPULAUAN RIAU",
                        "description": ""
                    },
                    {
                        "code": "LAMPUNG",
                        "value": "LAMPUNG",
                        "description": ""
                    },
                    {
                        "code": "MALUKU",
                        "value": "MALUKU",
                        "description": ""
                    },
                    {
                        "code": "MALUKU UTARA",
                        "value": "MALUKU UTARA",
                        "description": ""
                    },
                    {
                        "code": "NUSA TENGGARA BARAT",
                        "value": "NUSA TENGGARA BARAT",
                        "description": ""
                    },
                    {
                        "code": "NUSA TENGGARA TIMUR",
                        "value": "NUSA TENGGARA TIMUR",
                        "description": ""
                    },
                    {
                        "code": "PAPUA",
                        "value": "PAPUA",
                        "description": ""
                    },
                    {
                        "code": "PAPUA BARAT",
                        "value": "PAPUA BARAT",
                        "description": ""
                    },
                    {
                        "code": "RIAU",
                        "value": "RIAU",
                        "description": ""
                    },
                    {
                        "code": "SULAWESI BARAT",
                        "value": "SULAWESI BARAT",
                        "description": ""
                    },
                    {
                        "code": "SULAWESI SELATAN",
                        "value": "SULAWESI SELATAN",
                        "description": ""
                    },
                    {
                        "code": "SULAWESI TENGAH",
                        "value": "SULAWESI TENGAH",
                        "description": ""
                    },
                    {
                        "code": "SULAWESI TENGGARA",
                        "value": "SULAWESI TENGGARA",
                        "description": ""
                    },
                    {
                        "code": "SULAWESI UTARA",
                        "value": "SULAWESI UTARA",
                        "description": ""
                    },
                    {
                        "code": "SUMATERA BARAT",
                        "value": "SUMATERA BARAT",
                        "description": ""
                    },
                    {
                        "code": "SUMATERA SELATAN",
                        "value": "SUMATERA SELATAN",
                        "description": ""
                    },
                    {
                        "code": "SUMATERA UTARA",
                        "value": "SUMATERA UTARA",
                        "description": ""
                    }
                ]
            },
            "response_code": "00000"
        }
