## Fetch Sub District Parameter [/parameter/subDistrict]

### Fetch Sub District Parameter [POST]

+ Request (application/json)

        {
            "provinceCode" : "RIAU",
            "cityCode" : "Indragiri Hulu, Kab.",
            "districtCode" : "RENGAT"
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "parameters": [
                    {
                        "code": "KAMPUNG BESAR KOTA",
                        "value": "KAMPUNG BESAR KOTA",
                        "description": ""
                    },
                    {
                        "code": "KAMPUNG BESAR SEBERANG",
                        "value": "KAMPUNG BESAR SEBERANG",
                        "description": ""
                    },
                    {
                        "code": "KAMPUNG DAGANG",
                        "value": "KAMPUNG DAGANG",
                        "description": ""
                    },
                    {
                        "code": "KAMPUNG PULAU",
                        "value": "KAMPUNG PULAU",
                        "description": ""
                    },
                    {
                        "code": "KUANTAN BARU",
                        "value": "KUANTAN BARU",
                        "description": ""
                    },
                    {
                        "code": "PASAR KOTA",
                        "value": "PASAR KOTA",
                        "description": ""
                    },
                    {
                        "code": "PASAR KOTA RENGAT",
                        "value": "PASAR KOTA RENGAT",
                        "description": ""
                    },
                    {
                        "code": "PASIR KEMILU",
                        "value": "PASIR KEMILU",
                        "description": ""
                    },
                    {
                        "code": "PULAU GAJAH",
                        "value": "PULAU GAJAH",
                        "description": ""
                    },
                    {
                        "code": "RANTAU MAPESAI",
                        "value": "RANTAU MAPESAI",
                        "description": ""
                    },
                    {
                        "code": "RAWA BANGUN",
                        "value": "RAWA BANGUN",
                        "description": ""
                    },
                    {
                        "code": "SEI GUNTUNG HILIR",
                        "value": "SEI GUNTUNG HILIR",
                        "description": ""
                    },
                    {
                        "code": "SEI GUNTUNG TENGAH",
                        "value": "SEI GUNTUNG TENGAH",
                        "description": ""
                    },
                    {
                        "code": "SEKIP HILIR",
                        "value": "SEKIP HILIR",
                        "description": ""
                    },
                    {
                        "code": "SEKIP HULU",
                        "value": "SEKIP HULU",
                        "description": ""
                    },
                    {
                        "code": "SUNGAI BERINGIN",
                        "value": "SUNGAI BERINGIN",
                        "description": ""
                    },
                    {
                        "code": "SUNGAI RAYA",
                        "value": "SUNGAI RAYA",
                        "description": ""
                    }
                ]
            },
            "response_code": "00000"
        }
