
## Primary bonds Inquiry Detail Mutual Funds [/wealth/mutualfund/inquiry-detail]

### Primary bonds Inquiry Detail Mutual Funds [POST]

+ Request (application/json)
        
        {
            "productCode":"BNPCS"
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "response_code": "00000",
            "data": {
                "navDate": "2021-03-16T17:00:00.000+00:00",
                "navAmount": 1906.7334,
                "productId": 10,
                "productCode": "RDISP",
                "productCurrency": "IDR",
                "productName": "ABERDEEN STANDARD IND EQUITY FUND",
                "productCategory": "EQUITY FUND",
                "productRiskProfile": "Aggressive",
                "totalAum": 7777777,
                "totalAumFormatted": "7.8 M",
                "isAllowRecurring": true,
                "isAllowInsurance": false,
                "minLumpsump": 100000,
                "minRecurring": 50000,
                "minRedeem": 0,
                "minSwitch": 0,
                "minRedeemUnit": "IDR",
                "minSwitchUnit": "Unit",
                "subsFee": 1,
                "suitabilityBit": false,
                "urlProspektus": "https://www.ocbcnisp.com/OCBC-NISP-Staging/media/NISPOnline/Personal%20Banking/Wealth%20Management/Reksa%20Dana/Prospektus/2014/2014_-Propektus-NISP-INDEKS-SAHAM-PROGRESIF.pdf",
                "urlFundFactSheet": "https://www.ocbcnisp.com/OCBC-NISP-Staging/media/NISPOnline/Personal%20Banking/Wealth%20Management/Reksa%20Dana/Fund%20Factsheet/2015/March/315-Aberdeen-Indonesia-Equity-Fund-Mar-15-Bhs.pdf",
                "listPerformance": [
                    {
                        "performType": "1D",
                        "performTitle": "Daily",
                        "percentage": 0,
                        "profitAmount": 1906.7334
                    },
                    {
                        "performType": "1W",
                        "performTitle": "Weekly",
                        "percentage": -23.94,
                        "profitAmount": 1906.7334
                    },
                    {
                        "performType": "1M",
                        "performTitle": "Monthly",
                        "percentage": -17.62,
                        "profitAmount": 1906.7334
                    },
                    {
                        "performType": "1Y",
                        "performTitle": "Yearly",
                        "percentage": -5.25,
                        "profitAmount": 1906.7334
                    }
                ],
                "listAssetAllocation": [
                    {
                        "alokasiDesc": "PasarUang",
                        "alokasiPercentage": 20,
                        "color": "#710013"
                    },
                    {
                        "alokasiDesc": "PendapatanTetap",
                        "alokasiPercentage": 10,
                        "color": "#c41432"
                    },
                    {
                        "alokasiDesc": "Saham",
                        "alokasiPercentage": 70,
                        "color": "#005073"
                    }
                ],
                "listClientCode": [
                    {
                        "clientId": 88804,
                        "clientCode": "ISP00092273",
                        "isRDB": true,
                        "unitBalance": 599.5803,
                        "amountBalance": 1143239.78399202
                    },
                    {
                        "clientId": 89004,
                        "clientCode": "ISP00092492",
                        "isRDB": true,
                        "unitBalance": 1930.283,
                        "amountBalance": 3680535.0675522
                    }
                ]
            }
        }
