
## Validate Register [/wealth/investment/register/validate]

### Validate Register [POST]

+ Request (application/json)

        {
            "referenceNumber": "NTI202104141926202737",
            "isAgreeRiskProfile": true
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "tncCode": "REGISTERINVESTMENT",
                "onlineSessionId": "2021-04-14T20:44:06.217+217:217-8fa45f01-91a5-4a2e-b070-3e9990b6c53f"
            },
            "response_code": "00000"
        }
