
## Upload NPWP [/wealth/investment/register/npwp]

### Upload NPWP [POST]

+ Request (application/json)

        {
            "referenceNumber": "NTI202104081127522720",
            "file": "base64format",
            "npwp" : {
                "number":"31751014046700053"
            }
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "response_code": "00000"
        }
