
## Get Wealth Detail [/wealth/investment/detail]

### Get Wealth Detail [POST]

1. REGISTER
2. RISKPROFILE
3. REGISTERINVESTOR

+ Request (application/json)

        {
            "code": "REGISTER"
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "title": "Complete Personal Data Now",
                "subtitle": "Get ready",
                "description": "<p><strong>Complete Your Personal Data</strong></p>\n<p>To best guide you in investing, there are a few information  that you need to complete.</p>\n<p>After you have completed all the information , you can start investing via ONe Mobile within a maximum of 2 days.</p>",
                "image": "base64format"
            },
            "response_code": "00000"
        }
