
## Inquiry Register Source Of Fund [/wealth/investment/register/source-of-fund]

### Inquiry Register Source Of Fund [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "accounts": [
                    {
                        "productCode": "GRRMCY9902",
                        "productName": "GIRO BUSINESS SMART",
                        "accountNo": "693800000723",
                        "accountType": "D",
                        "branchCode": "99693",
                        "mcBit": "Y",
                        "accountId": "AE28BF3D6C4EDA13E050A8C0940711A9",
                        "labelDebitAccount": "GIRO BUSINESS SMART 693800000723 IDR 65200583.00",
                        "cif": "0000000000001679512",
                        "accountBalances": [
                            {
                                "accountCcy": "IDR",
                                "balance": 65200583,
                                "isAvailable": true
                            }
                        ]
                    },
                    {
                        "productCode": "GRRMCY9902",
                        "productName": "GIRO BUSINESS SMART",
                        "accountNo": "693800004501",
                        "accountType": "D",
                        "branchCode": "99693",
                        "mcBit": "Y",
                        "accountId": "AE28BF3D6C5DDA13E050A8C0940711A9",
                        "labelDebitAccount": "GIRO BUSINESS SMART 693800004501 EUR 1.41",
                        "cif": "0000000000001679512",
                        "accountBalances": [
                            {
                                "accountCcy": "IDR",
                                "balance": 410525298.23,
                                "isAvailable": true
                            },
                            {
                                "accountCcy": "EUR",
                                "balance": 1.41,
                                "isAvailable": true
                            },
                            {
                                "accountCcy": "USD",
                                "balance": 50,
                                "isAvailable": true
                            }
                        ]
                    },
                    {
                        "productCode": "GRRMCY9902",
                        "productName": "GIRO BUSINESS SMART",
                        "accountNo": "693800005508",
                        "accountType": "D",
                        "branchCode": "99693",
                        "mcBit": "Y",
                        "accountId": "AE28BF3D6C61DA13E050A8C0940711A9",
                        "labelDebitAccount": "GIRO BUSINESS SMART 693800005508 AUD 0.00",
                        "cif": "0000000000001679512",
                        "accountBalances": [
                            {
                                "accountCcy": "IDR",
                                "balance": -100000,
                                "isAvailable": true
                            },
                            {
                                "accountCcy": "AUD",
                                "balance": 0,
                                "isAvailable": false
                            },
                            {
                                "accountCcy": "CAD",
                                "balance": 0,
                                "isAvailable": false
                            },
                            {
                                "accountCcy": "CHF",
                                "balance": 0,
                                "isAvailable": false
                            },
                            {
                                "accountCcy": "CNH",
                                "balance": 0,
                                "isAvailable": false
                            },
                            {
                                "accountCcy": "EUR",
                                "balance": 0,
                                "isAvailable": false
                            },
                            {
                                "accountCcy": "GBP",
                                "balance": 0,
                                "isAvailable": false
                            },
                            {
                                "accountCcy": "HKD",
                                "balance": 0,
                                "isAvailable": false
                            },
                            {
                                "accountCcy": "JPY",
                                "balance": 0,
                                "isAvailable": false
                            },
                            {
                                "accountCcy": "NZD",
                                "balance": 0,
                                "isAvailable": false
                            },
                            {
                                "accountCcy": "SGD",
                                "balance": 0,
                                "isAvailable": true
                            },
                            {
                                "accountCcy": "USD",
                                "balance": 0,
                                "isAvailable": false
                            }
                        ]
                    }
                ]
            },
            "response_code": "00000"
        }
