
## Primary bonds Apply Mutual Funds [/wealth/mutualfund/apply]

### Primary bonds Apply Mutual Funds [POST]

+ Request (application/json)
        
        {
            "productCurrency": IDR
        }

+ Response 200 (application/json)
        

        {
            "responseDescription": "SUKSES", 
            "responseTitle": "",
            "language": "IN",
            "data": {},
            "response_code": "00000"
        }
