
## Activate Device [/user/activate-device]

### Activate Device [POST]

Validation:
Device yang bisa melakukan aktivasi device hanya device primary, dengan kata lain device secondary tidak bisa melakukan aktivasi device.

+ Request (application/json)

        {
            "executorDevice": {
                "deviceId":"895e985f-7b48-46",
                "deviceFingerPrint": "0340ECED62CA7778DE9B040DAFD50A2656FB66C445CDAC74D49997E832DB79DC",
                "isPrimary": true,
                "isActive": true
            },
            "targetDevice" : {
                "deviceId":"895e985f-7b48-46",
                "channel":"MB",
                "deviceModel":"device Model string",
                "deviceType":"red mi note",
                "deviceOs":"android 9.0",
                "isRooted":"false",
                "deviceFingerPrint": "0340ECED62CA7778DE9B040DAFD50A2656FB66C445CDAC74D49997E832DB79DC"
            }
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES"
        }
