
## Forgot Password [/user/forgot/password]

### Forgot Password [POST]

Note: Diakses dari menu Forgot Password tanpa session.

+ Request (application/json)

        {
            "cif": "9234972398423",
            "userName": "JOHNWICK6666",
            "randomID": "7868123123",
            "paramsC": "iojf9812bkw0912b3",
            "paramsP": "kjsf98b1230jkfoasd"
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES"
        }
