
## Login / Authenticate [/user/authenticate]

### Login [POST]

+ Request

        {
            "paramsC": "20866639466054D8E7ABEB4E068CA35875A897BDE0AD0B900E03AB876F5BBC37DDD804F805A3EF4A5D45D6327A277939AD1F0938928E426C80A8A86F5FA42DC7512E674C705EDBC2D174D3D8D62CA8DE0FE7A7212B5A3A1ADFC35C043310FC62AF68E0E111E21FBD2344E576C0FCF574EF5C0BDAEEB01F47A28F146FF3185536",
            "paramsP": "F6360672C6EFDE9052D4528E3070CBDB",
            "randomID": "20210323060552",
            "deviceBindingParameters": {
                "isRooted": false,
                "deviceOs": "14.4",
                "cif": "",
                "deviceFingerPrint": "99B09ACAD927C3197DE7508BCB6D8EE2322F8A4E2E7645E78FD93687F6EC97F2",
                "pushToken": "",
                "dateBind": "",
                "deviceModel": "iPhone 12 Pro",
                "deviceType": "iPhone",
                "deviceId": "C771435F-CE64-4AC8-BEB2-B47E0DE3CF83",
                "userCd": ""
            },
            "userName": "AULIARAC1511"
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "deviceBindingResponse": {
                    "maxDevices": 2,
                    "bypassPinTransaction": false,
                    "isPrimary": false,
                    "isActive": true
                },
                "restAuthenticationTokenResponse": {
                    "authorities": [{
                        "authority": "ROLE_USER"
                    }],
                    "authenticated": true,
                    "userName": "AULIARAC1511",
                    "paramsC": "2EA0527A9212AB11FBFFFECDEB33696FBFF5F07C01FD039524E68D02D2930670847E1679B5055F1DDE5CD5E0A14B61C8CD956C91DA9CBB4D004919E6F8FDF59F730BC52C7541504CFBB6F8E7A25236B7DF625B9534CA25A7557832FA4204B0152B2FDCB32839F982E88AD705F29DE6C57624E3448A6581A88E57091DF1E565AE",
                    "paramsP": "BEFF882489523C813DB0AF7FA64AD091",
                    "randomID": "20200904073519",
                    "userCif": "0000000000001679512",
                    "sessionId": "2A70E37432187D09D9A29897A16B4E11",
                    "user": {
                        "createdBy": "AULIARAC1511-MB",
                        "guid": "282b62206a297ec4d0bf6f3c8cd83b62",
                        "userId": "AULIARAC1511",
                        "userCode": "AULIARAC1511",
                        "nickname": "AULIA RACHMAN",
                        "dateOfBirth": "1987-11-14T17:00:00.000+0000",
                        "cif": "0000000000001679512",
                        "sessionId": "2A70E37432187D09D9A29897A16B4E11",
                        "currentLogin": "2020-09-04T00:35:39.000+0000",
                        "randomID": "20200904073519",
                        "roleCode": "ROLE_USER",
                        "isChangePassword": false,
                        "primaryDevice": {
                            "dateBind": "2020-10-13T07:08:46.000+00:00",
                            "deviceModel": "Xiaomi",
                            "deviceType": "MI 9",
                            "deviceOs": "android 10"
                        },
                        "inactiveDevices": [
                            {
                                "deviceId": "f5b43ac5-d36c-4f",
                                "cif": "0000000000002139882",
                                "userCd": "DIANA1234",
                                "dateBind": "2020-10-13T07:08:46.000+00:00",
                                "deviceModel": "Xiaomi",
                                "deviceType": "MI 9",
                                "isRooted": false,
                                "deviceOs": "android 10",
                                "deviceFingerPrint": "112233"
                            },
                            {
                                "deviceId": "fjhs73jf91-s123-g3",
                                "cif": "0000000000002139882",
                                "userCd": "DIANA1234",
                                "dateBind": "2020-10-14T07:08:46.000+00:00",
                                "deviceModel": "iPhone 11 Pro",
                                "deviceType": "iPhone 11 Pro",
                                "isRooted": false,
                                "deviceOs": "iOS 14.5",
                                "deviceFingerPrint": "556688"
                            }
                        ],
                        "listAccountPerCIF": [{
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBPOINT001",
                            "accountCcy": "",
                            "accountNo": "000010098929",
                            "accountType": "Y",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "IDR",
                            "accountNo": "693800000723",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "IDR",
                            "accountNo": "693800004501",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "IDR",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "IDR",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "IDR",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "USD",
                            "accountNo": "693800004501",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "USD",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "USD",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "USD",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "SGD",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "SGD",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "SGD",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "JPY",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "JPY",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "JPY",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "EUR",
                            "accountNo": "693800004501",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "EUR",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "EUR",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "EUR",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "AUD",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "AUD",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "AUD",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "HKD",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "HKD",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "HKD",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "GBP",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "GBP",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "GBP",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "CAD",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "CAD",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "CAD",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "CHF",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "CHF",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "CHF",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "NZD",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "NZD",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "NZD",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "CNH",
                            "accountNo": "693800005508",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "CNH",
                            "accountNo": "693800005516",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "GRRMCY9902",
                            "accountCcy": "CNH",
                            "accountNo": "693800005599",
                            "accountType": "D",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBMDIB0001",
                            "accountCcy": "IDR",
                            "accountNo": "127810001819",
                            "accountType": "S",
                            "branchCode": "70127",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBMDIB0101",
                            "accountCcy": "USD",
                            "accountNo": "127810001827",
                            "accountType": "S",
                            "branchCode": "70127",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBMDIB0001",
                            "accountCcy": "IDR",
                            "accountNo": "127810001868",
                            "accountType": "S",
                            "branchCode": "70127",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBMDIB0101",
                            "accountCcy": "USD",
                            "accountNo": "127810001876",
                            "accountType": "S",
                            "branchCode": "70127",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBTND13082",
                            "accountCcy": "IDR",
                            "accountNo": "562810000025",
                            "accountType": "S",
                            "branchCode": "01562",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "562810000041",
                            "accountType": "S",
                            "branchCode": "01562",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBPAY10002",
                            "accountCcy": "IDR",
                            "accountNo": "693810003337",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "IDR",
                            "accountNo": "693810021354",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "IDR",
                            "accountNo": "693810021529",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "IDR",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24033",
                            "accountCcy": "IDR",
                            "accountNo": "693810023681",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023699",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023707",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023715",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023723",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023756",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023764",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023772",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023798",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023806",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023814",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023830",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023855",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023863",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023871",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023889",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24038",
                            "accountCcy": "IDR",
                            "accountNo": "693810023897",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKASR24034",
                            "accountCcy": "IDR",
                            "accountNo": "693810028094",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22034",
                            "accountCcy": "IDR",
                            "accountNo": "693810033730",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22034",
                            "accountCcy": "IDR",
                            "accountNo": "693810033961",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22033",
                            "accountCcy": "IDR",
                            "accountNo": "693810034100",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22034",
                            "accountCcy": "IDR",
                            "accountNo": "693810034118",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22038",
                            "accountCcy": "IDR",
                            "accountNo": "693810034126",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22038",
                            "accountCcy": "IDR",
                            "accountNo": "693810034183",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22033",
                            "accountCcy": "IDR",
                            "accountNo": "693810034191",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22033",
                            "accountCcy": "IDR",
                            "accountNo": "693810034209",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22033",
                            "accountCcy": "IDR",
                            "accountNo": "693810034225",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "IDR",
                            "accountNo": "693810036170",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22033",
                            "accountCcy": "IDR",
                            "accountNo": "693810037087",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22033",
                            "accountCcy": "IDR",
                            "accountNo": "693810038457",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKFIXNA003",
                            "accountCcy": "IDR",
                            "accountNo": "693810039505",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22033",
                            "accountCcy": "IDR",
                            "accountNo": "693810039513",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22033",
                            "accountCcy": "IDR",
                            "accountNo": "693810039604",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "IDR",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKFIXNA003",
                            "accountCcy": "IDR",
                            "accountNo": "693810040024",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22033",
                            "accountCcy": "IDR",
                            "accountNo": "693810040032",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKNAS22038",
                            "accountCcy": "IDR",
                            "accountNo": "693810040073",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "IDR",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKFIXAS003",
                            "accountCcy": "IDR",
                            "accountNo": "693810040644",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKFIXAS003",
                            "accountCcy": "IDR",
                            "accountNo": "693810040651",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKFIXAS003",
                            "accountCcy": "IDR",
                            "accountNo": "693810040677",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKFIXAS003",
                            "accountCcy": "IDR",
                            "accountNo": "693810040685",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TKFIXAS003",
                            "accountCcy": "IDR",
                            "accountNo": "693810040693",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "USD",
                            "accountNo": "693810021529",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "USD",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "USD",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "USD",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "SGD",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "SGD",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "SGD",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "JPY",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "JPY",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "JPY",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "EUR",
                            "accountNo": "693810021529",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "EUR",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "EUR",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "EUR",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "AUD",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "AUD",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "AUD",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "HKD",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "HKD",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "HKD",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "GBP",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "GBP",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "GBP",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "CAD",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "CAD",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "CAD",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "CHF",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "CHF",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "CHF",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "NZD",
                            "accountNo": "693810021529",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "NZD",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "NZD",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "NZD",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "CNH",
                            "accountNo": "693810022139",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "CNH",
                            "accountNo": "693810040008",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "TBSMCY9901",
                            "accountCcy": "CNH",
                            "accountNo": "693810040099",
                            "accountType": "S",
                            "branchCode": "99693",
                            "mcBit": "Y",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DBIDIB0001",
                            "accountCcy": "IDR",
                            "accountNo": "127820000108",
                            "accountType": "T",
                            "branchCode": "70127",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DBECCB0003",
                            "accountCcy": "IDR",
                            "accountNo": "693820005397",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DBECCB0001",
                            "accountCcy": "IDR",
                            "accountNo": "693820009886",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010058",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010074",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010819",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010843",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010850",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010868",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DBIDIB0001",
                            "accountCcy": "IDR",
                            "accountNo": "693820010876",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010918",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010926",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010934",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010942",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010959",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820010967",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820011007",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DHECCB0014",
                            "accountCcy": "IDR",
                            "accountNo": "693820011023",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DBECIB0003",
                            "accountCcy": "IDR",
                            "accountNo": "693820011163",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }, {
                            "createdBy": "AULIARAC1511",
                            "productCode": "DBECCB0001",
                            "accountCcy": "IDR",
                            "accountNo": "693820011189",
                            "accountType": "T",
                            "branchCode": "99693",
                            "mcBit": "N",
                            "userCode": "AULIARAC1511",
                            "cif": "0000000000001679512"
                        }],
                        "listCustomerTokenDto": [{
                            "returnCode": 0,
                            "serialNo": "VDS1000131",
                            "deviceNumber": "VDS1000131",
                            "tokenTypeNo": "SW"
                        }, {
                            "returnCode": 0,
                            "serialNo": "VDP0000002",
                            "deviceNumber": "VDP0000002",
                            "tokenTypeNo": "HW"
                        }, {
                            "returnCode": 0,
                            "serialNo": "VDP0000002",
                            "deviceNumber": "8567456546",
                            "tokenTypeNo": "SMS"
                        }],
                        "isEOD": false,
                        "migrationStatus": "0",
                        "fullName": "AULIA RACHMAN",
                        "uuid": "87CF67BB-8853-4BA4-8E0A-8A1F8AF2407F"
                    },
                    "principal": "AULIARAC1511",
                    "name": "AULIARAC1511"
                }
            }
        }