
## Logout [/user/logoutprocess]

### Logout [POST]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES"
        }