
## Generate Random Number [/user/random_number]

### Generate Random Number [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "randomNumberResponse": {
                    "randomId": "20200901094031",
                    "randomNumber": "8BFD23F10CBA47548B597A7E1CEB6448"
                }
            }
        }
