
## Prelogin Data [/user/pre-login-data]

### Prelogin Data [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "listPreLoginResponse": [
                    {
                        "id": "1",
                        "page": 1,
                        "quoteEn": "Owning a House is Not Just a Dream ",
                        "quoteId": "Bisa Punya Rumah Bukan Cuma Mimpi",
                        "learnMoreEn": "https://www.ocbcnisp.com/personal-banking/kredit/Kredit-Kepemilikan-Apertemen/Overview-Kredit-Kepemilikan-Rumah.aspx",
                        "learnMoreId": "https://www.ocbcnisp.com/personal-banking/kredit/Kredit-Kepemilikan-Apertemen/Overview-Kredit-Kepemilikan-Rumah.aspx"
                    }
                ]
            }
        }