        
## Profile Detail [/user/profile-user-detail]

### Profile User Detail [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "referenceNumber" : "AA91089C-CC4F-4066-83E8-A97781160E33",
                "personalInformation": {
                    "email": "mbank.user09@devteam.net",
                    "religion": "Moslem",
                    "maritalStatus": "Married",
                    "lastEducation": ""
                },
                "financialInformation": {
                    "netIncome": ">100 M - 500 M",
                    "averageTransaction": ">100 M - 500 M",
                    "lastEducation": ""
                },
                "mailingAddressInformation": {
                    "address": "JL PERJUANGAN GG BUNTU RT : 1 RW : 1",
                    "province": "DKI JAKARTA",
                    "kabupaten": "KOTA ADM. JAKARTA UTARA",
                    "kecamatan": "KOJA",
                    "kelurahan": "TUGU SELATAN",
                    "postalCode": "0"
                },
                "businessInformation": {
                    "workType": "Civil Servant / PNS",
                    "companyName": "kelurahan jamika",
                    "industry": "OTHER THAN LISTED INDUSTRIES",
                    "jobsTitle": "Manager/Unit Head"
                },
                "businessAddress": {
                    "address": "sup alamat RT :  RW :",
                    "province": "DKI JAKARTA",
                    "kabupaten": "Jakarta Barat, Wil. Kota",
                    "kecamatan": "KEBON JERUK",
                    "kelurahan": "KEDOYA SELATAN",
                    "postalCode": "11520"
                },
                "RqUuid": "a4fde0a3-fd9a-4cb6-85d7-6a1dab2b95be",
                "userInformation": {
                    "password": null,
                    "userFuid": null,
                    "userId": "AFF75576BB428815E050A8C094075556",
                    "userCode": "NANA7777",
                    "userPIN": null,
                    "nickname": "ENDANG MUSTIKOWATI",
                    "userName": "ENDANG MUSTIKOWATI",
                    "dateOfBirth": "1985-02-01T17:00:00.000+00:00",
                    "cif": "0000000000002139040",
                    "trxSeqNo": null,
                    "sessionId": "C3A194955E4456AC48A16D7FB30D1674",
                    "lastLogin": "2021-03-13T08:54:55.000+00:00",
                    "lastLogout": "2020-09-23T08:04:29.000+00:00",
                    "timeCreated": "2020-09-23T08:04:29.000+00:00",
                    "timeUpdated": "2021-03-14T01:20:10.000+00:00",
                    "version": 782,
                    "isLogged": true,
                    "isDeleted": null,
                    "image": null,
                    "lastLoginFailure": "2021-01-21T15:20:35.000+00:00",
                    "currentLogin": "2021-03-14T01:20:10.000+00:00",
                    "createdBy": null,
                    "updatedBy": null,
                    "randomID": null,
                    "roleCode": null,
                    "isChangePassword": false,
                    "listAccountPerCIF": null,
                    "oldPass": null,
                    "newPass": null,
                    "confNewPass": null,
                    "paramsC": null,
                    "paramsP": null,
                    "userResponseSuccessMessage": null,
                    "userResponseFailedMessage": null,
                    "listCustomerTokenDto": null,
                    "file": null,
                    "fileString": null,
                    "email": null,
                    "isManuallyChangedPassword": null,
                    "statusKYC": null,
                    "isEOD": null,
                    "deviceNumber": null,
                    "userDevice": null,
                    "migrationStatus": null,
                    "fullName": null,
                    "uuid": null,
                    "segment": null
                }
            },
            "response_code": "00000"
        }
