
## User: Register User Internet Banking [/user/register-user-internet-banking]

### Register User Internet Banking [POST]

+ Request (application/json)

        {
            "uniqueIdentifier": "3409u18978wyhu3o8bdo",
            "userId": "TAYLOR1111",
            "cif": "8728930919020",
            "ccNumber": "0000000000000181",
            "fullName": "Taylor Dewi",
            "email": "test@test.com",
            "requestId" : "83167ffc-584d-4243-905a-8fba93b03a23",
            "phoneNumber" : "0831234124"
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {}
        }
