
## Register Change Password [/register/change_password]

### Register Change Password [POST]

Note: Diakses dari menu Setting menggunakan session

+ Request (application/json)

        {
            "randomID":"791346",
            "cif":"0000000000001636025",
            "userName":"POINT8181",
            "paramsC":"0",
            "paramsP":"AD267D601414F0FB40FCEFAD6FDF5BAC"       
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "response_code": "00000"
        }