
## Reset Password [/user/reset_password_username]

### Reset Password [POST]

RegistraionCd List
1. registrationCd = PASSWORD untuk forgot password
2. registrationCd = USERNAME untuk forgot username

Format dateOfBirthStr = ddmmyyyy

+ Request (application/json)

        {
            "operationCode" : "000",
            "registerInternetBankingForm" : {
                "uniqueIdentifier": "23125erdfe123rw3r",
                "registrationCd":"USERNAME",
                "dateOfBirthStr":"01012000",
                "phoneNumber":"081220011636",
                "cif":"0000000000000181",
                "ccNumber":"0000000000000181"
            }
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "response_code": "00000"
        }


