## Personal Info Update [/user/profile/update/personal-info]

### Personal Info Update [POST]

+ Request (application/json)

        {
            "referenceNumber":"012345678910",
            "emailStatement": "rafa@gmail.com",
            "nickname": "Rafa Doank"
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {},
            "response_code": "00000"
        }
