
## Dukcapil [/account/dukcapil]

### Dukcapil [POST]

+ Request (application/json)

        {
            "referenceNumber":"010203040506",
            "ktpNumber": "1231231236454"
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "name": "mukegile",
                "address": "jalan kenangan"
            }
        }
