
## Account Products Category Detail [/account/product/accounts]

### Account Products Category Detail [POST]

+ Request (application/json)

        {
            "accountProductId": "AEEE3E1EC7602D79E050A8C0940779C2"
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "accountProductDetails": [ {
                    "id": "AEEF1AD65EA82AEBE050A8C094071175",
                    "productCode": "TANDA002",
                    "productTitle": "Saving Account",
                    "title": "Tanda 360 Plus",
                    "subtitle": "he flexibility to save money and do transactions using 12 different currencies in 1 saving account",
                    "description": "<p>Tanda 360 Plus offers you the convenience and freedom for your everyday banking transactions with 12 different currencies in just 1 account: IDR, USD, SGD, EUR, AUD, JPY, GBP, HKD, CAD, CHF, NZD &amp; CNH<br /><br />Free of fees by maintaining your monthly average balance min. IDR 10 Million*:<br />- Free Admin fee<br />- Free Interbank transfer fee via Mobile/Internet Banking up to 30 transactions<br />- Free Interbank transfer fee via ATM up to 30 transactions<br /><br />*Terms and conditions applied</p>",
                    "encodedImage": ""
                }, {
                    "id": "B3B85A1ABA3D2E6SQ050A8C094077D9A",
                    "productCode": "TAKAFIX",
                    "productTitle": "Saving Plan",
                    "title": "TAKA Fix Installment",
                    "subtitle": "Plan your future now!",
                    "description": "<p>Need to raise money for various plans, but don't have time to go to the bank and open an account?<br /><br />Come on, make all plans starting today with TAKA and don't delay it anymore!<br /><br />Tabungan Berjangka TAKA is a savings that provides certainty of funds for your future plans.<br /><br />For more information, please visit:</p>",
                    "encodedImage": ""
                }, {
                    "id": "AEEF3241D4F169D3E050A8C0940731C2",
                    "productCode": "TAKABUNGA",
                    "productTitle": "Saving Plan",
                    "title": "TAKA Interest",
                    "subtitle": "Term savings based on final target savings with flexible interest rates",
                    "description": "<p>Perlu mengumpulkan uang untuk berbagai rencana, tapi tak punya waktu buat ke bank dan buka rekening?<br /><br />Yuk, wujudkan semua rencana mulai hari ini dengan TAKA dan jangan tunda lagi!</p>",
                    "encodedImage": ""
                }, {
                    "id": "AEEF3241D4F169D3E050A8C0940731C9",
                    "productCode": "TKNAS22038",
                    "productTitle": "Saving Plan",
                    "title": "TAKA Cashback",
                    "subtitle": "Term savings based on final target savings with flexible interest rates",
                    "description": "<p>Perlu mengumpulkan uang untuk berbagai rencana, tapi tak punya waktu buat ke bank dan buka rekening?<br /><br />Yuk, wujudkan semua rencana mulai hari ini dengan TAKA dan jangan tunda lagi!</p>",
                    "encodedImage": ""
                }, {
                    "id": "B0E339E1E6D3BFEBE050A8C0940723E6",
                    "productCode": "TNSYR001",
                    "productTitle": "Saving Account",
                    "title": "Tabungan Mudharabah",
                    "subtitle": "Solution for all you business transaction",
                    "description": "<style>body {background-color: white;}</style><p>Layanan perbankan untuk pengusaha muda yang ingin mengembangkan bisnis sekaligus mengelola keuangan pribadi.<br><br>Dua tabungan terpisah, Tabungan Personal &amp; Giro Bisnis<br>- Bebas biaya admin rekening<br>- Bebas biaya tarik tunai di ATM mana saja,<br>- Bebas biaya transfer ke bank mana pun,<br>- Akses pinjaman komfirmasi instan<br>- Tersedia Deposito Online dengan tenor 2 minggu<br><br>KELOLA TRANSAKSI BISNIS DAN PERSONAL SECARA TERPISAH DI REKENING TABUNGAN</p>",
                    "encodedImage": ""
                }, {
                    "id": "AEEDE0B28D13BCC6E050A8C094077098",
                    "productCode": "AOPRD001",
                    "productTitle": "Time Deposite",
                    "title": "Time Deposite",
                    "subtitle": "Time Deposite",
                    "description": "<style>body {background-color: white;}</style><p>Layanan perbankan untuk pengusaha muda yang ingin mengembangkan bisnis sekaligus mengelola keuangan pribadi.<br><br>Dua tabungan terpisah, Time Deposite<br>- Bebas biaya admin rekening<br>- Bebas biaya tarik tunai di ATM mana saja,<br>- Bebas biaya transfer ke bank mana pun,<br>- Akses pinjaman komfirmasi instan<br>- Tersedia Deposito Online dengan tenor 2 minggu<br></p>",
                    "encodedImage": ""
                }]
            }
        }
