
## TAKA Fix Disbursement [/account/saving/plan/fix/disbursement]

### TAKA Fix Disbursement [POST]

+ Request (application/json)

        {
            "currencies" : ["IDR"]
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUCCESS",
            "data": {
                "accountName": "ENDANG MUSTIKOWATI",
                "accounts": [
                    {
                        "productCode": "TBSMCY9902",
                        "productName": "Tanda360Plus-Digital",
                        "accountNo": "693810030363",
                        "accountType": "S",
                        "branchCode": "99693",
                        "mcBit": "Y",
                        "accountId": "B58C0D5AF6B33D48E050A8C09407517C",
                        "cif": "0000000000002139206",
                        "accountBalances": [
                            {
                                "accountCcy": "IDR",
                                "balance": 377753.64,
                                "isAvailable": true
                            }
                        ]
                    }
                ]
            }
        }
