
## TAKA Target Calculate [/account/saving/plan/target/calculate]

### TAKA Target Calculate [POST]

+ Request (application/json)

        {
            "installmentAmount" : 10000000,
            "initialAmount" : 5000000,
            "tenor" : 1
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "accountType": "S",
                "currencyCode": "IDR",
                "productCode": "TKNAS22034",
                "tncCode": "TAKATRGT",
                "installmentAmount": 820778.0,
                "initialAmount": 0,
                "tenor": 1
            },
            "response_code": "00000"
        }
