
## TAKA Fix Apply [/account/saving/plan/fix/apply]

### TAKA Fix Apply [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUCCESS",
            "data": {
                "email": "kim@gmail.com",
                "minAmount": 100000
            }
        }
