
## TAKA Target Apply [/account/saving/plan/target/apply]

### TAKA Target Apply [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUCCESS",
            "data": {
                "email": "kim@gmail.com",
                "minAmount": 2000000,
                "multiplier": 1000000
            }
        }
