
## TAKA Cashback Apply [/account/saving/plan/cashback/apply]

### TAKA Cashback Apply [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "email": "A@gmail.com",
                "rewards": [
                    {
                        "cashbackValue": "780000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 24,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 990435,
                                "initialSaving": 1121250,
                                "targetAmount": 25000000,
                                "penalty": 1121250,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM001     ",
                                "giftName": "Cashback Taka Online Rp 780ribu nett    "
                            },
                            {
                                "tenor": 30,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 625673,
                                "initialSaving": 1121250,
                                "targetAmount": 20000000,
                                "penalty": 1121250,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM002     ",
                                "giftName": "Cashback Taka Online Rp 780ribu nett    "
                            },
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 437989,
                                "initialSaving": 1121250,
                                "targetAmount": 17000000,
                                "penalty": 1121250,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM003     ",
                                "giftName": "Cashback Taka Online Rp 780ribu nett    "
                            }
                        ]
                    },
                    {
                        "cashbackValue": "7800000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 24,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 9904354,
                                "initialSaving": 11212500,
                                "targetAmount": 250000000,
                                "penalty": 11212500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM004     ",
                                "giftName": "Cashback Taka Online Rp 7,8juta nett    "
                            },
                            {
                                "tenor": 30,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 6256730,
                                "initialSaving": 11212500,
                                "targetAmount": 200000000,
                                "penalty": 11212500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM005     ",
                                "giftName": "Cashback Taka Online Rp 7,8juta nett    "
                            },
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 4379890,
                                "initialSaving": 11212500,
                                "targetAmount": 170000000,
                                "penalty": 11212500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM006     ",
                                "giftName": "Cashback Taka Online Rp 7,8juta nett    "
                            },
                            {
                                "tenor": 48,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 2450852,
                                "initialSaving": 11212500,
                                "targetAmount": 130000000,
                                "penalty": 11212500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM007     ",
                                "giftName": "Cashback Taka Online Rp 7,8juta nett    "
                            },
                            {
                                "tenor": 60,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 1593048,
                                "initialSaving": 11212500,
                                "targetAmount": 108000000,
                                "penalty": 11212500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM008     ",
                                "giftName": "Cashback Taka Online Rp 7,8juta nett    "
                            }
                        ]
                    },
                    {
                        "cashbackValue": "2500000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 2798312,
                                "initialSaving": 3593750,
                                "targetAmount": 105000000,
                                "penalty": 3593750,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM0071    ",
                                "giftName": "Cashback - Rp 2.5juta nett              "
                            },
                            {
                                "tenor": 48,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 1784275,
                                "initialSaving": 3593750,
                                "targetAmount": 90000000,
                                "penalty": 3593750,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM0072    ",
                                "giftName": "Cashback - Rp 2.5juta nett              "
                            },
                            {
                                "tenor": 60,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 1094362,
                                "initialSaving": 3593750,
                                "targetAmount": 70000000,
                                "penalty": 3593750,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM0073    ",
                                "giftName": "Cashback - Rp 2.5juta nett              "
                            }
                        ]
                    },
                    {
                        "cashbackValue": "5000000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 5596624,
                                "initialSaving": 7187500,
                                "targetAmount": 210000000,
                                "penalty": 7187500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM0074    ",
                                "giftName": "Cashback - Rp 5juta nett                "
                            },
                            {
                                "tenor": 60,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 2188724,
                                "initialSaving": 7187500,
                                "targetAmount": 140000000,
                                "penalty": 7187500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM0075    ",
                                "giftName": "Cashback - Rp 5juta nett                "
                            },
                            {
                                "tenor": 24,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 7168172,
                                "initialSaving": 7187500,
                                "targetAmount": 180000000,
                                "penalty": 7187500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM017     ",
                                "giftName": "Cashback Rp 5 juta                      "
                            },
                            {
                                "tenor": 48,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 1915454,
                                "initialSaving": 7187500,
                                "targetAmount": 100000000,
                                "penalty": 7187500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM019     ",
                                "giftName": "Cashback Rp 5 juta                      "
                            }
                        ]
                    },
                    {
                        "cashbackValue": "10000000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 11193247,
                                "initialSaving": 14375000,
                                "targetAmount": 420000000,
                                "penalty": 14375000,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM0076    ",
                                "giftName": "Cashback - Rp 10juta nett               "
                            },
                            {
                                "tenor": 48,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 6620507,
                                "initialSaving": 14375000,
                                "targetAmount": 335000000,
                                "penalty": 14375000,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM0077    ",
                                "giftName": "Cashback - Rp 10juta nett               "
                            },
                            {
                                "tenor": 60,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 4245464,
                                "initialSaving": 14375000,
                                "targetAmount": 272000000,
                                "penalty": 14375000,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM0078    ",
                                "giftName": "Cashback - Rp 10juta nett               "
                            }
                        ]
                    },
                    {
                        "cashbackValue": "500000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 18,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 1344453,
                                "initialSaving": 718750,
                                "targetAmount": 25000000,
                                "penalty": 718750,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM010     ",
                                "giftName": "Cashback Rp 500ribu                     "
                            },
                            {
                                "tenor": 24,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 716817,
                                "initialSaving": 718750,
                                "targetAmount": 18000000,
                                "penalty": 718750,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM011     ",
                                "giftName": "Cashback Rp 500ribu                     "
                            },
                            {
                                "tenor": 30,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 473347,
                                "initialSaving": 718750,
                                "targetAmount": 15000000,
                                "penalty": 718750,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM012     ",
                                "giftName": "Cashback Rp 500ribu                     "
                            },
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 394021,
                                "initialSaving": 718750,
                                "targetAmount": 15000000,
                                "penalty": 718750,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM031     ",
                                "giftName": "Cashback - Rp 500ribu nett              "
                            }
                        ]
                    },
                    {
                        "cashbackValue": "1000000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 18,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 2412006,
                                "initialSaving": 1437500,
                                "targetAmount": 45000000,
                                "penalty": 1437500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM013     ",
                                "giftName": "Cashback Rp 1 juta                      "
                            },
                            {
                                "tenor": 24,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 1599608,
                                "initialSaving": 1437500,
                                "targetAmount": 40000000,
                                "penalty": 1437500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM014     ",
                                "giftName": "Cashback Rp 1 juta                      "
                            },
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 650008,
                                "initialSaving": 1437500,
                                "targetAmount": 25000000,
                                "penalty": 1437500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM015     ",
                                "giftName": "Cashback Rp 1 juta                      "
                            },
                            {
                                "tenor": 48,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 383091,
                                "initialSaving": 1437500,
                                "targetAmount": 20000000,
                                "penalty": 1437500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM016     ",
                                "giftName": "Cashback Rp 1 juta                      "
                            },
                            {
                                "tenor": 30,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 1112502,
                                "initialSaving": 1437500,
                                "targetAmount": 35000000,
                                "penalty": 1437500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM032     ",
                                "giftName": "Cashback - Rp 1 juta nett               "
                            },
                            {
                                "tenor": 60,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 305762,
                                "initialSaving": 1437500,
                                "targetAmount": 20000000,
                                "penalty": 1437500,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM035     ",
                                "giftName": "Cashback - Rp 1 juta nett               "
                            }
                        ]
                    },
                    {
                        "cashbackValue": "790000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 30,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 824160,
                                "initialSaving": 1135625,
                                "targetAmount": 26000000,
                                "penalty": 1135625,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM021     ",
                                "giftName": "Cashback Rp790ribu nett                 "
                            },
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 575622,
                                "initialSaving": 1135625,
                                "targetAmount": 22000000,
                                "penalty": 1135625,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM022     ",
                                "giftName": "Cashback Rp790ribu nett                 "
                            },
                            {
                                "tenor": 48,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 348102,
                                "initialSaving": 1135625,
                                "targetAmount": 18000000,
                                "penalty": 1135625,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM023     ",
                                "giftName": "Cashback Rp790ribu nett                 "
                            }
                        ]
                    },
                    {
                        "cashbackValue": "7900000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 30,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 8241602,
                                "initialSaving": 11356250,
                                "targetAmount": 260000000,
                                "penalty": 11356250,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM024     ",
                                "giftName": "Cashback Rp7.9 juta nett                "
                            },
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 5756217,
                                "initialSaving": 11356250,
                                "targetAmount": 220000000,
                                "penalty": 11356250,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM025     ",
                                "giftName": "Cashback Rp7.9 juta nett                "
                            },
                            {
                                "tenor": 48,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 3274382,
                                "initialSaving": 11356250,
                                "targetAmount": 170000000,
                                "penalty": 11356250,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM026     ",
                                "giftName": "Cashback Rp7.9 juta nett                "
                            },
                            {
                                "tenor": 60,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 2201048,
                                "initialSaving": 11356250,
                                "targetAmount": 145000000,
                                "penalty": 11356250,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM027     ",
                                "giftName": "Cashback Rp7.9 juta nett                "
                            }
                        ]
                    },
                    {
                        "cashbackValue": "250000",
                        "currency": "IDR ",
                        "groupProgCode": "13",
                        "descGroupProgCode": "13",
                        "groupProgType": "NP",
                        "listAvailableProd": [
                            {
                                "tenor": 30,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 319577,
                                "initialSaving": 359375,
                                "targetAmount": 10000000,
                                "penalty": 359375,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM028     ",
                                "giftName": "Cashback - Rp 250ribu nett              "
                            },
                            {
                                "tenor": 36,
                                "productCode": "TKNAS22038",
                                "monthlyInstallment": 210814,
                                "initialSaving": 359375,
                                "targetAmount": 8000000,
                                "penalty": 359375,
                                "interestRate": 0.5,
                                "programCode": "13",
                                "giftCode": "OM029     ",
                                "giftName": "Cashback - Rp 250ribu nett              "
                            }
                        ]
                    }
                ]
            },
            "response_code": "00000"
        }
