
## Mudharabah Confirmation [/account/saving/account/mudharabah/confirmation]

### Mudharabah Confirmation [POST]

+ Request (application/json)

        {
            "purpose": "B",
            "sourceOfFund": "A",
            "otp": "",
            "name": null,
            "email": "kim@gmail.com",
            "phoneNumber": null,
            "address": null,
            "ccyCode": null,
            "productCode": null,
            "productType": null,
            "mcyBit": null,
            "createAtm": "N",
            "sendAtm": "N",
            "initialDeposit": null,
            "mudharabahRate": null,
            "nisbahSpesial": null,
            "nisbahSpesialCode": null,
            "conventionalRate": null,
            "conventionalRateDesc": null
        }

+ Response 200 (application/json)

        {
                "response_code": "00000",
                "response_desc_en": "SUCCESS",
                "response_desc_id": "SUCCESS",
                "data": {
                        "purpose": "B",
                        "sourceOfFund": "A",
                        "otp": "",
                        "name": null,
                        "email": "kim@gmail.com",
                        "phoneNumber": null,
                        "address": null,
                        "ccyCode": null,
                        "productCode": null,
                        "productType": null,
                        "mcyBit": null,
                        "createAtm": "N",
                        "sendAtm": "N",
                        "initialDeposit": null,
                        "mudharabahRate": null,
                        "nisbahSpesial": null,
                        "nisbahSpesialCode": null,
                        "conventionalRate": null,
                        "conventionalRateDesc": null,
                        "onlineSessionId": "693810053779--1000000-30ad6495-318e-4969-9850-e560b1ad3af0"
                }
        }
