## Apply 360 [/account/tanda360/apply]

### Apply 360 [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "baseCurrencies": [{
                    "prodCode": "TANDA0001",
                    "ccyCode": "IDR",
                    "minimumAmount": 200000,
                    "maximumAmount": 1000000
                }, {
                    "prodCode": "TANDA0002",
                    "ccyCode": "SGD",
                    "minimumAmount": 100,
                    "maximumAmount": 10000
                }, {
                    "prodCode": "TANDA0003",
                    "ccyCode": "USD",
                    "minimumAmount": 100,
                    "maximumAmount": 10000
                }, {
                    "prodCode": "TANDA0004",
                    "ccyCode": "HKD",
                    "minimumAmount": 1000,
                    "maximumAmount": 20000
                }, {
                    "prodCode": "TANDA0005",
                    "ccyCode": "AUD",
                    "minimumAmount": 100,
                    "maximumAmount": 20000
                }, {
                    "prodCode": "TANDA0006",
                    "ccyCode": "CAD",
                    "minimumAmount": 100,
                    "maximumAmount": 20000
                }, {
                    "prodCode": "TANDA0007",
                    "ccyCode": "CHF",
                    "minimumAmount": 100,
                    "maximumAmount": 20000
                }, {
                    "prodCode": "TANDA0008",
                    "ccyCode": "CNH",
                    "minimumAmount": 1000,
                    "maximumAmount": 20000
                }, {
                    "prodCode": "TANDA0009",
                    "ccyCode": "EUR",
                    "minimumAmount": 100,
                    "maximumAmount": 20000
                }, {
                    "prodCode": "TANDA0010",
                    "ccyCode": "GBP",
                    "minimumAmount": 100,
                    "maximumAmount": 20000
                }, {
                    "prodCode": "TANDA0011",
                    "ccyCode": "JPY",
                    "minimumAmount": 10000,
                    "maximumAmount": 20000
                }, {
                    "prodCode": "TANDA0012",
                    "ccyCode": "NZD",
                    "minimumAmount": 100,
                    "maximumAmount": 20000
                }],
                "name": "MARIANA",
                "email": null,
                "phoneNumber": null,
                "deadlineDeposit": 3,
                "address": {
                    "address": "ADDR2 243",
                    "postalCode": "35111",
                    "province": "LAMPUNG",
                    "districtCity": "KOTA BDR LAMPUNG",
                    "kecamatan": "TANJUNGKARANG PUSAT",
                    "kelurahan": "TANJUNG KARANG"
                }
            },
            "response_code": "00000"
        }