
## Get Source Of Fund TimeDeposit [/account/time/deposit/source-of-funds]

### Get Source Of Fund TimeDeposit [POST]

+ Request (application/json)

        {
            "currencies" : ["IDR"]
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "accountName": "NAME2 1419",
                "accounts": [
                    {
                        "productCode": "GRRMCY9902",
                        "productName": "GIRO BUSINESS SMART",
                        "accountNo": "133800000076",
                        "accountType": "D",
                        "accountCcy": "",
                        "branchCode": "05133",
                        "mcBit": "Y",
                        "dynamicAccountId": "",
                        "bankCode": "999",
                        "bankName": "",
                        "description": "",
                        "qrCode": "",
                        "accountBalances": [
                            {
                                "accountCcy": "IDR",
                                "balance": 10194872617,
                                "holdBalance": 0,
                                "isAvailable": true,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            }
                        ]
                    },
                    {
                        "productCode": "TBPAY10002",
                        "productName": "TANDA PAYROLL 1-P",
                        "accountNo": "141810000358",
                        "accountType": "S",
                        "accountCcy": "",
                        "branchCode": "05141",
                        "mcBit": "N",
                        "dynamicAccountId": "",
                        "bankCode": "999",
                        "bankName": "",
                        "description": "",
                        "qrCode": "",
                        "accountBalances": [
                            {
                                "accountCcy": "IDR",
                                "balance": 6915662509,
                                "holdBalance": 0,
                                "isAvailable": true,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            }
                        ]
                    },
                    {
                        "productCode": "TBTND13082",
                        "productName": "TND360 PROMO3 2012-S|TANDAEnglish",
                        "accountNo": "133810018381",
                        "accountType": "S",
                        "accountCcy": "",
                        "branchCode": "05133",
                        "mcBit": "N",
                        "dynamicAccountId": "",
                        "bankCode": "999",
                        "bankName": "",
                        "description": "",
                        "qrCode": "",
                        "accountBalances": [
                            {
                                "accountCcy": "IDR",
                                "balance": 955421706.59,
                                "holdBalance": 0,
                                "isAvailable": true,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            }
                        ]
                    },
                    {
                        "productCode": "TBSMCY9901",
                        "productName": "Tanda360Plus-S",
                        "accountNo": "133810018498",
                        "accountType": "S",
                        "accountCcy": "",
                        "branchCode": "05133",
                        "mcBit": "Y",
                        "dynamicAccountId": "",
                        "bankCode": "999",
                        "bankName": "",
                        "description": "",
                        "qrCode": "",
                        "accountBalances": [
                            {
                                "accountCcy": "IDR",
                                "balance": 100810855411.99,
                                "holdBalance": 0,
                                "isAvailable": true,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            }
                        ]
                    },
                    {
                        "productCode": "TBSMCY9901",
                        "productName": "Tanda360Plus-S",
                        "accountNo": "693810017378",
                        "accountType": "S",
                        "accountCcy": "",
                        "branchCode": "99693",
                        "mcBit": "Y",
                        "dynamicAccountId": "",
                        "bankCode": "999",
                        "bankName": "",
                        "description": "",
                        "qrCode": "",
                        "accountBalances": [
                            {
                                "accountCcy": "IDR",
                                "balance": 7223773,
                                "holdBalance": 0,
                                "isAvailable": true,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            }
                        ]
                    }
                ]
            },
            "response_code": "00000"
        }
