
## confirmation [/account/time/deposit/confirmation]

### confirmation [POST]

+ Request (application/json)

        {
            "productCode" : "AOPRD001",
            "productName" : "Deposito",
            "depositProductCode" : "DBECCB0001",
            "email": "mbank.user08@devteam.net",
            "currency": "IDR",
            "amount": 5000000,
            "tenor": "1-M",
            "maturity": "AOMAT001",
            "interestPayment": "1-M",
            "promoCode" : "ERN00002",
            "tncCode": "TIMEDEPOSIT_IDR",
            "sourceOfFundName": "Pendapatan",
            "purposeName": "Investasi",
            "interestRate": 5.12,
            "sourceOfFund": {
                "productCode": "TBSMCY9901",
                "productName": "Tanda360Plus-S",
                "accountNo": "133810018498",
                "accountType": "S",
                "accountName": "NAME2 1419",
                "accountCcy": "",
                "branchCode": "05133",
                "mcBit": "Y",
                "dynamicAccountId": "",
                "bankCode": "999",
                "bankName": "",
                "description": "",
                "qrCode": "",
                "accountBalances": [
                    {
                        "accountCcy": "IDR",
                        "balance": 100810855411.99,
                        "holdBalance": 0,
                        "isAvailable": true,
                        "accountCcyNameID": "Rupiah Indonesia",
                        "accountCcyNameEN": "Indonesian Rupiah"
                    }
                ]
            }
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "productCode": "AOPRD001",
                "productName": "Deposito",
                "depositProductCode": "DBECCB0001",
                "email": "mbank.user08@devteam.net",
                "currency": "IDR",
                "amount": 5000000,
                "tenor": "3-M",
                "maturity": "AOMAT001",
                "interestPayment": "3-M",
                "promoCode" : "ERN00002",
                "tncCode": "TIMEDEPOSIT",
                "sourceOfFundName": "Pendapatan",
                "purposeName": "Investasi",
                "interestRate": 5.12,
                "sourceOfFund": {
                    "productCode": "TBSMCY9901",
                    "productName": "Tanda360Plus-S",
                    "accountNo": "133810018498",
                    "accountType": "S",
                    "accountName": "NAME2 1419",
                    "accountCcy": "",
                    "branchCode": "05133",
                    "mcBit": "Y",
                    "dynamicAccountId": "",
                    "bankCode": "999",
                    "bankName": "",
                    "description": "",
                    "qrCode": "",
                    "accountBalances": [
                        {
                            "accountCcy": "IDR",
                            "balance": 100810855411.99,
                            "holdBalance": 0,
                            "isAvailable": true,
                            "accountCcyNameID": "Rupiah Indonesia",
                            "accountCcyNameEN": "Indonesian Rupiah"
                        }
                    ]
                },
                "onlineSessionId" : "693810053779--1000000-30ad6495-318e-4969-9850-e560b1ad3af0"
            },
            "response_code": "00000"
        }
