
## Dashboard: Inquiry Credit Account Balance [/dashboard/inquiry-credit-account-balance]

### Inquiry Credit Account Balances [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "response_code": "00000",
            "data": {
                "loans": [
                    {
                        "code": "CC",
                        "title": "CC",
                        "image" : "https://byonimage.blob.core.windows.net/dashboard/cc.png",
                        "totals": [
                            {
                                "accountCcy": "IDR",
                                "balance": 8599065943.62,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            }
                        ],
                        "accounts": [
                            {
                                "accountNo": "14730510048",
                                "cardNumber": "4215613300000018",
                                "creditLimit": 100000000,
                                "availableCredit": 72703836,
                                "currentBalance": 27296164,
                                "minimumPayment": 2729617,
                                "dueDate": "2020-10-09T00:00:00.000+00:00",
                                "outstandingBalance": 27296164,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "voyage",
                                "pointAvailable": "4600",
                                "cardColor": [
                                    "#AF9177",
                                    "#F2D3B0"
                                ]
                            },
                            {
                                "accountNo": "14730520047",
                                "cardNumber": "4215613300000026",
                                "creditLimit": 1500000000,
                                "availableCredit": 1464901891,
                                "currentBalance": 35098109,
                                "minimumPayment": 3509811,
                                "dueDate": "2020-10-09T00:00:00.000+00:00",
                                "outstandingBalance": 35098109,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "voyage",
                                "pointAvailable": "600",
                                "cardColor": [
                                    "#AF9177",
                                    "#F2D3B0"
                                ]
                            },
                            {
                                "accountNo": "14730540045",
                                "cardNumber": "4215615500000011",
                                "creditLimit": 300000000,
                                "availableCredit": 270960001,
                                "currentBalance": 32016752,
                                "minimumPayment": 3201676,
                                "dueDate": "2020-10-04T00:00:00.000+00:00",
                                "outstandingBalance": 32016752,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "voyage",
                                "pointAvailable": "0",
                                "cardColor": [
                                    "#AF9177",
                                    "#F2D3B0"
                                ]
                            },
                            {
                                "accountNo": "14730410041",
                                "cardNumber": "4215618800001259",
                                "creditLimit": 3000000000,
                                "availableCredit": 1844677499.34,
                                "currentBalance": 1155302500.66,
                                "minimumPayment": 115530251,
                                "dueDate": "2020-10-05T00:00:00.000+00:00",
                                "outstandingBalance": 1155302500.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "normal visa",
                                "cardColor": [
                                    "#AF9177",
                                    "#F2D3B0"
                                ]
                            },
                            {
                                "accountNo": "14730420040",
                                "cardNumber": "4215618800001267",
                                "creditLimit": 3100000000,
                                "availableCredit": 1908622166.34,
                                "currentBalance": 1191169500.66,
                                "minimumPayment": 119116951,
                                "dueDate": "2020-10-05T00:00:00.000+00:00",
                                "outstandingBalance": 1191169500.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "normal visa",
                                "cardColor": [
                                    "#AF9177",
                                    "#F2D3B0"
                                ]
                            },
                            {
                                "accountNo": "14730420040",
                                "cardNumber": "4215618800001275",
                                "creditLimit": 3100000000,
                                "availableCredit": 1908622166.34,
                                "currentBalance": 0,
                                "minimumPayment": 119116951,
                                "dueDate": "2020-10-05T00:00:00.000+00:00",
                                "outstandingBalance": 1191169500.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "voyage",
                                "pointAvailable": "0",
                                "cardColor": [
                                    "#AF9177",
                                    "#F2D3B0"
                                ]
                            },
                            {
                                "accountNo": "14730450047",
                                "cardNumber": "4645821100000555",
                                "creditLimit": 1700000000,
                                "availableCredit": -508379712.66,
                                "currentBalance": 2163332927.66,
                                "minimumPayment": 2139124369.66,
                                "dueDate": "2020-11-14T00:00:00.000+00:00",
                                "outstandingBalance": 2139124369.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "kta",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "",
                                    ""
                                ]
                            },
                            {
                                "accountNo": "14730450047",
                                "cardNumber": "4645821100000563",
                                "creditLimit": 1700000000,
                                "availableCredit": -508379712.66,
                                "currentBalance": 0,
                                "minimumPayment": 2139124369.66,
                                "dueDate": "2020-11-14T00:00:00.000+00:00",
                                "outstandingBalance": 2139124369.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "kta",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "",
                                    ""
                                ]
                            },
                            {
                                "accountNo": "7370330040",
                                "cardNumber": "4645831100000364",
                                "creditLimit": 15000000,
                                "availableCredit": 13386785,
                                "currentBalance": 1613215,
                                "minimumPayment": 1613215,
                                "dueDate": "2020-10-05T00:00:00.000+00:00",
                                "outstandingBalance": 1613215,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "visa platinum",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "#939793",
                                    "#CDCDCD"
                                ]
                            },
                            {
                                "accountNo": "14730350049",
                                "cardNumber": "4645831100010850",
                                "creditLimit": 1500000000,
                                "availableCredit": 479859999.34,
                                "currentBalance": 1020140000.66,
                                "minimumPayment": 102014001,
                                "dueDate": "2020-10-05T00:00:00.000+00:00",
                                "outstandingBalance": 1020140000.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "visa platinum",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "#939793",
                                    "#CDCDCD"
                                ]
                            },
                            {
                                "accountNo": "14730360048",
                                "cardNumber": "4645831100010868",
                                "creditLimit": 1600000000,
                                "availableCredit": 573492999.34,
                                "currentBalance": 1026802000.66,
                                "minimumPayment": 102680201,
                                "dueDate": "2020-10-09T00:00:00.000+00:00",
                                "outstandingBalance": 1026802000.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "visa platinum",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "#939793",
                                    "#CDCDCD"
                                ]
                            },
                            {
                                "accountNo": "14730360048",
                                "cardNumber": "4645831100010876",
                                "creditLimit": 1600000000,
                                "availableCredit": 573492999.34,
                                "currentBalance": 0,
                                "minimumPayment": 102680201,
                                "dueDate": "2020-10-09T00:00:00.000+00:00",
                                "outstandingBalance": 1026802000.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "visa platinum",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "#939793",
                                    "#CDCDCD"
                                ]
                            },
                            {
                                "accountNo": "7371250049",
                                "cardNumber": "5241691100000631",
                                "creditLimit": 15000000,
                                "availableCredit": 8436838,
                                "currentBalance": 6388772,
                                "minimumPayment": 6388772,
                                "dueDate": "2020-10-05T00:00:00.000+00:00",
                                "outstandingBalance": 6388772,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "mastercard titanium",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "#0060e6",
                                    "#002a76"
                                ]
                            },
                            {
                                "accountNo": "14730380046",
                                "cardNumber": "5241691100004732",
                                "creditLimit": 2000000000,
                                "availableCredit": 1015212499.34,
                                "currentBalance": 985320000.66,
                                "minimumPayment": 98532001,
                                "dueDate": "2020-10-09T00:00:00.000+00:00",
                                "outstandingBalance": 985320000.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "mastercard titanium",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "#0060e6",
                                    "#002a76"
                                ]
                            },
                            {
                                "accountNo": "14730390045",
                                "cardNumber": "5241691100004740",
                                "creditLimit": 2100000000,
                                "availableCredit": 1145385666.34,
                                "currentBalance": 954586000.66,
                                "minimumPayment": 95458601,
                                "dueDate": "2020-10-05T00:00:00.000+00:00",
                                "outstandingBalance": 954586000.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "mastercard titanium",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "#0060e6",
                                    "#002a76"
                                ]
                            },
                            {
                                "accountNo": "14730390045",
                                "cardNumber": "5241691100004757",
                                "creditLimit": 2100000000,
                                "availableCredit": 1145385666.34,
                                "currentBalance": 0,
                                "minimumPayment": 95458601,
                                "dueDate": "2020-10-05T00:00:00.000+00:00",
                                "outstandingBalance": 954586000.66,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "mastercard titanium",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "#0060e6",
                                    "#002a76"
                                ]
                            }
                        ]
                    },
                    {
                        "code": "KTA",
                        "title": "KTA",
                        "image" : "https://byonimage.blob.core.windows.net/dashboard/kta.png",
                        "totals": [
                            {
                                "accountCcy": "IDR",
                                "balance": 4246667,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            }
                        ],
                        "accounts": [
                            {
                                "accountNo": "14730440048",
                                "cardNumber": "6034398600004290",
                                "creditLimit": 50000000,
                                "availableCredit": 0,
                                "currentBalance": 4246667,
                                "minimumPayment": 4246667,
                                "dueDate": "2020-10-05T00:00:00.000+00:00",
                                "outstandingBalance": 4246667,
                                "accountCcy": "IDR",
                                "accountType": "C",
                                "source": "CB",
                                "productName": "kta",
                                "pointAvailable": 0,
                                "cardColor": [
                                    "",
                                    ""
                                ]
                            }
                        ]
                    }
                ]
            }
        }
