
## Dashboard: Inquiry Total Balances [/dashboard/inquiry-balance-total]

### Inquiry Total Balances (Active Balance) [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "listAccountBalanceByCIF": [
                    {
                        "accountCcyNameID": "IDR ID",
                        "accountCcyNameEN": "IDR EN",
                        "accountCcy": "IDR",
                        "balance": 1497382669.02,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "USD ID",
                        "accountCcyNameEN": "USD EN",
                        "accountCcy": "USD",
                        "balance": 1957483.55,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "SGD ID",
                        "accountCcyNameEN": "SGD EN",
                        "accountCcy": "SGD",
                        "balance": 1046737.69,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "JPY ID",
                        "accountCcyNameEN": "JPY EN",
                        "accountCcy": "JPY",
                        "balance": 930202.64,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "EUR ID",
                        "accountCcyNameEN": "EUR EN",
                        "accountCcy": "EUR",
                        "balance": 2000059.41,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "AUD ID",
                        "accountCcyNameEN": "AUD EN",
                        "accountCcy": "AUD",
                        "balance": 1002176.55,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "HKD ID",
                        "accountCcyNameEN": "HKD EN",
                        "accountCcy": "HKD",
                        "balance": 999800,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "GBP ID",
                        "accountCcyNameEN": "GBP EN",
                        "accountCcy": "GBP",
                        "balance": 1005081.55,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "CAD ID",
                        "accountCcyNameEN": "CAD EN",
                        "accountCcy": "CAD",
                        "balance": 1000000,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "CHF ID",
                        "accountCcyNameEN": "CHF EN",
                        "accountCcy": "CHF",
                        "balance": 999980,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "NZD ID",
                        "accountCcyNameEN": "NZD EN",
                        "accountCcy": "NZD",
                        "balance": 2000400,
                        "isAvailable": true
                    },
                    {
                        "accountCcyNameID": "CNH ID",
                        "accountCcyNameEN": "CNH EN",
                        "accountCcy": "CNH",
                        "balance": 1001714.4,
                        "isAvailable": true
                    }
                ]
            }
        }
