
## CC Transaction Histories [/dashboard/cc-transaction/histories]

### CC Transaction Histories [POST]

+ Request (application/json)

        {
            "accountNo" : "4645831100011189",
            "accountCcy" : "IDR",
            "page" : 1,
            "countPerPage" : 10
        }

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "responseDescription": "SUCCESS",
            "language": "IN",
            "data": {
                "resultCode": "1000",
                "message": "Success",
                "page": 1,
                "countPerPage": 10,
                "totalAllData": 15,
                "data": {
                    "transactionDetails": [
                        {
                            "transactionDate": "07/09/2020",
                            "description": "DUMMY MERCHANT JAKARTARE ID ",
                            "amount": 2000000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-07",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "123014",
                            "accNo": "7372760053",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "103",
                            "oriAmount": "2000000",
                            "mcc": "7011",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "true",
                            "listIPP": [
                            {
                                "cardNumber": "4645831100011478",
                                "transactionAuthNo": "101222",
                                "programName": "IPP3b",
                                "tenor": 3,
                                "interest": 1.5,
                                "interestAmount": 15000,
                                "adminFee": 15000,
                                "installmentBalance": 348333
                            }]
                        },
                        {
                            "transactionDate": "07/09/2020",
                            "description": "BIAYA NOTIFIKASI                        ",
                            "amount": 5000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-07",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "      ",
                            "accNo": "7372760020",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "126",
                            "oriAmount": "5000",
                            "mcc": "    ",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "07/09/2020",
                            "description": "BIAYA NOTIFIKASI                        ",
                            "amount": 5000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-07",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "      ",
                            "accNo": "7372760020",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "126",
                            "oriAmount": "5000",
                            "mcc": "    ",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "07/09/2020",
                            "description": "BIAYA NOTIFIKASI                        ",
                            "amount": 5000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-07",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "      ",
                            "accNo": "7372760020",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "126",
                            "oriAmount": "5000",
                            "mcc": "    ",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "07/09/2020",
                            "description": "BIAYA NOTIFIKASI                        ",
                            "amount": 5000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-07",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "      ",
                            "accNo": "7372760020",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "126",
                            "oriAmount": "5000",
                            "mcc": "    ",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "07/09/2020",
                            "description": "BIAYA NOTIFIKASI                        ",
                            "amount": 5000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-07",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "      ",
                            "accNo": "7372760020",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "126",
                            "oriAmount": "5000",
                            "mcc": "    ",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "07/09/2020",
                            "description": "BIAYA NOTIFIKASI                        ",
                            "amount": 5000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-07",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "      ",
                            "accNo": "7372760020",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "126",
                            "oriAmount": "5000",
                            "mcc": "    ",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "07/09/2020",
                            "description": "CASH ADVANCE FEE                        ",
                            "amount": 80000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-07",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "",
                            "accNo": "7372760020",
                            "oriCurrency": "",
                            "pem": "",
                            "tc": "550",
                            "oriAmount": "0",
                            "mcc": "",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "05/09/2020",
                            "description": "DUMMY MERCHANT          JAKARTARE    ID ",
                            "amount": 6000000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-05",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "332211",
                            "accNo": "7372760046",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "5",
                            "oriAmount": "6000000",
                            "mcc": "7011",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "04/09/2020",
                            "description": "DUMMY MERCHANT          JAKARTARE    ID ",
                            "amount": 1500000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-04",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "101252",
                            "accNo": "7372760046",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "5",
                            "oriAmount": "1500000",
                            "mcc": "7011",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "04/09/2020",
                            "description": "DUMMY MERCHANT          JAKARTARE    ID ",
                            "amount": 500000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-04",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "100001",
                            "accNo": "7372760046",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "5",
                            "oriAmount": "500000",
                            "mcc": "7011",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "04/09/2020",
                            "description": "PAYMENT (CASH), THANK YOU               ",
                            "amount": -46154148,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-09-04",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "",
                            "accNo": "7372760012",
                            "oriCurrency": "",
                            "pem": "",
                            "tc": "251",
                            "oriAmount": "0",
                            "mcc": "",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "21/08/2020",
                            "description": "CREDIT SHIELD BASE 3                    ",
                            "amount": 292227,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "4645831100011189",
                            "postingDate": "2020-08-21",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "      ",
                            "accNo": "7372760079",
                            "oriCurrency": "IDR",
                            "pem": "  ",
                            "tc": "143",
                            "oriAmount": "292227",
                            "mcc": "0000",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "20/04/2020",
                            "description": "STATEMNT BILL REQUEST FEE               ",
                            "amount": 10000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "7372760012",
                            "postingDate": "2020-04-20",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "",
                            "accNo": "7372760020",
                            "oriCurrency": "",
                            "pem": "",
                            "tc": "504",
                            "oriAmount": "0",
                            "mcc": "",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        },
                        {
                            "transactionDate": "20/04/2020",
                            "description": "OVERLIMIT CHARGE                        ",
                            "amount": 50000,
                            "currencyCode": null,
                            "period": "12009",
                            "creditCardNumber": null,
                            "productCode": "VISPL1",
                            "cardNo": "7372760012",
                            "postingDate": "2020-04-20",
                            "foreignCurrencyAmount": null,
                            "creditCardType": "0",
                            "authNo": "",
                            "accNo": "7372760020",
                            "oriCurrency": "",
                            "pem": "",
                            "tc": "519",
                            "oriAmount": "0",
                            "mcc": "",
                            "customerIdentificationNumber": null,
                            "authCode": null,
                            "eligibleInstallment": "false",
                            "listIPP": null
                        }
                    ],
                    "fromDate": "07 Sep 2020",
                    "toDate": "20 Apr 2020",
                    "countTransaction": "15"
                }
            }
        }