
## Dashboard: Inquiry Forex Rate [/dashboard/rate-forex]

### Inquiry Forex Rate [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "listExchangeRate": [
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "USD",
                        "currencyName": "USD EN",
                        "bankBuyRate": 13976,
                        "bankSellRate": 14076,
                        "ttBuyRate": 13976,
                        "ttSellRate": 14076,
                        "cbBuyRate": 14003,
                        "cbSellRate": 14049,
                        "cbRate": 14257,
                        "currencyUnit": 1,
                        "priorityIndex": 1,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "SGD",
                        "currencyName": "SGD EN",
                        "bankBuyRate": 10341.0836234,
                        "bankSellRate": 10439.7814005,
                        "ttBuyRate": 10341.0836234,
                        "ttSellRate": 10439.7814005,
                        "cbBuyRate": 10371.08,
                        "cbSellRate": 10409.78,
                        "cbRate": 10263.66,
                        "currencyUnit": 1,
                        "priorityIndex": 2,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "EUR",
                        "currencyName": "EUR EN",
                        "bankBuyRate": 15811.8678,
                        "bankSellRate": 16008.0752,
                        "ttBuyRate": 15811.8678,
                        "ttSellRate": 16008.0752,
                        "cbBuyRate": 15876.87,
                        "cbSellRate": 15943.08,
                        "cbRate": 15923.01,
                        "currencyUnit": 1,
                        "priorityIndex": 3,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "GBP",
                        "currencyName": "GBP EN",
                        "bankBuyRate": 18189.4124,
                        "bankSellRate": 18463.5456,
                        "ttBuyRate": 18189.4124,
                        "ttSellRate": 18463.5456,
                        "cbBuyRate": 18289.41,
                        "cbSellRate": 18363.55,
                        "cbRate": 17190.32,
                        "currencyUnit": 1,
                        "priorityIndex": 4,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "AUD",
                        "currencyName": "AUD EN",
                        "bankBuyRate": 9960.6306,
                        "bankSellRate": 10111.9632,
                        "ttBuyRate": 9960.6306,
                        "ttSellRate": 10111.9632,
                        "cbBuyRate": 10015.63,
                        "cbSellRate": 10056.96,
                        "cbRate": 9635.59,
                        "currencyUnit": 1,
                        "priorityIndex": 5,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "NZD",
                        "currencyName": "NZD EN",
                        "bankBuyRate": 9563.5746,
                        "bankSellRate": 9723.6192,
                        "ttBuyRate": 9563.5746,
                        "ttSellRate": 9723.6192,
                        "cbBuyRate": 9623.57,
                        "cbSellRate": 9663.62,
                        "cbRate": 9194.63,
                        "currencyUnit": 1,
                        "priorityIndex": 6,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "JPY",
                        "currencyName": "JPY EN",
                        "bankBuyRate": 125.3490344,
                        "bankSellRate": 127.9244669,
                        "ttBuyRate": 125.3490344,
                        "ttSellRate": 127.9244669,
                        "cbBuyRate": 126.35,
                        "cbSellRate": 126.92,
                        "cbRate": 135.34,
                        "currencyUnit": 1,
                        "priorityIndex": 7,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "HKD",
                        "currencyName": "HKD EN",
                        "bankBuyRate": 1775.5579446,
                        "bankSellRate": 1798.1242433,
                        "ttBuyRate": 1775.5579446,
                        "ttSellRate": 1798.1242433,
                        "cbBuyRate": 1783.56,
                        "cbSellRate": 1790.12,
                        "cbRate": 1816.16,
                        "currencyUnit": 1,
                        "priorityIndex": 8,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "CHF",
                        "currencyName": "CHF EN",
                        "bankBuyRate": 13945.59994,
                        "bankSellRate": 14110.0275137,
                        "ttBuyRate": 13945.59994,
                        "ttSellRate": 14110.0275137,
                        "cbBuyRate": 14000.6,
                        "cbSellRate": 14055.03,
                        "cbRate": 14629.33,
                        "currencyUnit": 1,
                        "priorityIndex": 9,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "CAD",
                        "currencyName": "CAD EN",
                        "bankBuyRate": 10602.6343431,
                        "bankSellRate": 10754.9771498,
                        "ttBuyRate": 10602.6343431,
                        "ttSellRate": 10754.9771498,
                        "cbBuyRate": 10657.63,
                        "cbSellRate": 10699.98,
                        "cbRate": 10764.21,
                        "currencyUnit": 1,
                        "priorityIndex": 10,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "CNH",
                        "currencyName": "CNH EN",
                        "bankBuyRate": 2038.2874869,
                        "bankSellRate": 2157.5218887,
                        "ttBuyRate": 2038.2874869,
                        "ttSellRate": 2157.5218887,
                        "cbBuyRate": 2093.29,
                        "cbSellRate": 2102.52,
                        "cbRate": 2092.5,
                        "currencyUnit": 1,
                        "priorityIndex": 11,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "CNY",
                        "currencyName": "CNY EN",
                        "bankBuyRate": 2028.6619592,
                        "bankSellRate": 2149.0597749,
                        "ttBuyRate": 2028.6619592,
                        "ttSellRate": 2149.0597749,
                        "cbBuyRate": 2083.66,
                        "cbSellRate": 2094.06,
                        "cbRate": 2016.65,
                        "currencyUnit": 1,
                        "priorityIndex": 99,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "IDR",
                        "currencyName": "IDR EN",
                        "bankBuyRate": 1,
                        "bankSellRate": 1,
                        "ttBuyRate": 1,
                        "ttSellRate": 1,
                        "cbBuyRate": 1,
                        "cbSellRate": 1,
                        "cbRate": 1,
                        "currencyUnit": 1,
                        "priorityIndex": 99,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "*AL",
                        "currencyName": "AL EN",
                        "bankBuyRate": 333.3333333,
                        "bankSellRate": 404,
                        "ttBuyRate": 333.3333333,
                        "ttSellRate": 404,
                        "cbBuyRate": 333.33,
                        "cbSellRate": 404,
                        "cbRate": 0,
                        "currencyUnit": 1,
                        "priorityIndex": 99,
                        "comma": 0
                    },
                    {
                        "timeCreated": "2020-05-26T08:23:14.000+00:00",
                        "currencyCode": "MYR",
                        "currencyName": "MYR EN",
                        "bankBuyRate": 3372.6632572,
                        "bankSellRate": 3529.6724541,
                        "ttBuyRate": 3372.6632572,
                        "ttSellRate": 3529.6724541,
                        "cbBuyRate": 3442.66,
                        "cbSellRate": 3459.67,
                        "cbRate": 3448.43,
                        "currencyUnit": 1,
                        "priorityIndex": 99,
                        "comma": 0
                    }
                ]
            }
        }
