
## Dashboard: Inquiry Loans [/dashboard/inquiry-loans]

### Inquiry Loans (Finance - My Savings) [GET]

+ Response 200 (application/json)

        {
            "responseDescription": "SUCCESS",
            "responseTitle": "",
            "language": "EN",
            "data": {
                "loans": [
                    {
                        "code": "KPR",
                        "title": "KPR",
                        "image" : "https://byonimage.blob.core.windows.net/dashboard/kpr.png",
                        "totals": [
                            {
                                "accountCcy": "IDR",
                                "balance": 86848614.00,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            },
                            {
                                "accountCcy": "USD",
                                "balance": 0,
                                "accountCcyNameID": "Dolar Amerika",
                                "accountCcyNameEN": "US Dollar"
                            }
                        ],
                        "accounts": [
                            {
                                "productCode": "KPRPRI_KND",
                                "productName": "KREDIT PEMILIKAN RUMAH",
                                "accountId": "BFCE5D54660754C7E053612810AC8AA8",
                                "accountNo": "520830009657",
                                "accountType": "L",
                                "branchCode": "02520",
                                "cif": "0000000000001103277",
                                "accountCcy": "IDR",
                                "balance": 0,
                                "availableBalance": 38424307,
                                "holdBalance" : 3600000000,
                                "overdraftBalance": 2585795906,
                                "monthlyPayment": 10000000,
                                "dueDate": "2021-03-16T17:00:00.000+00:00",
                                "maturityDate": "2031-03-16T17:00:00.000+00:00",
                                "interestRate": 0.0725,
                                "isSyariah" : false
                            },
                            {
                                "productCode": "KPRPRI_KND",
                                "productName": "KREDIT PEMILIKAN RUMAH",
                                "accountId": "BFCE5D54660754C7E053612810AC8AA9",
                                "accountNo": "520830009658",
                                "accountType": "L",
                                "branchCode": "02520",
                                "cif": "0000000000001103277",
                                "accountCcy": "IDR",
                                "balance": 0,
                                "availableBalance": 48424307,
                                "holdBalance" : 2600000000,
                                "overdraftBalance": 3585795906,
                                "monthlyPayment": 10000000,
                                "dueDate": "2021-03-16T17:00:00.000+00:00",
                                "maturityDate": "2031-03-16T17:00:00.000+00:00",
                                "interestRate": 0.0725,
                                "isSyariah" : false
                            }
                        ]
                    },
                    {
                        "code": "KPM",
                        "title": "KPM",
                        "image" : "https://byonimage.blob.core.windows.net/dashboard/kpm.png",
                        "totals": [
                            {
                                "accountCcy": "IDR",
                                "balance": 3951558.00,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            },
                            {
                                "accountCcy": "USD",
                                "balance": 0,
                                "accountCcyNameID": "Dolar Amerika",
                                "accountCcyNameEN": "US Dollar"
                            }
                        ],
                        "accounts": [
                            {
                                "productCode": "KPMCOPADVS",
                                "productName": "KPM",
                                "accountId": "BFCC4759E901721FE053612810AC8FB4",
                                "accountNo": "545830219972",
                                "accountType": "L",
                                "branchCode": "02545",
                                "cif": "0000000000001103277",
                                "accountCcy": "IDR",
                                "balance": 0,
                                "availableBalance": 3951558,
                                "holdBalance" : 187500000,
                                "overdraftBalance": 133931460,
                                "monthlyPayment": 10000000,
                                "dueDate": "2021-03-16T17:00:00.000+00:00",
                                "maturityDate": "2031-03-16T17:00:00.000+00:00",
                                "interestRate": 0.0725,
                                "isSyariah" : true
                            }
                        ]
                    },
                    {
                        "code": "KMG",
                        "title": "KMG",
                        "image" : "https://byonimage.blob.core.windows.net/dashboard/kmg.png",
                        "totals": [
                            {
                                "accountCcy": "IDR",
                                "balance": 5051558.00,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            },
                            {
                                "accountCcy": "USD",
                                "balance": 0,
                                "accountCcyNameID": "Dolar Amerika",
                                "accountCcyNameEN": "US Dollar"
                            }
                        ],
                        "accounts": [
                            {
                                "productCode": "KMG-XXXX",
                                "productName": "KMG",
                                "accountId": "BFCC4759E901721FE053612810AC8FB4",
                                "accountNo": "545830219972",
                                "accountType": "L",
                                "branchCode": "02545",
                                "cif": "0000000000001103277",
                                "accountCcy": "IDR",
                                "balance": 0,
                                "availableBalance": 3951558,
                                "holdBalance" : 187500000,
                                "overdraftBalance": 133931460,
                                "monthlyPayment": 10000000,
                                "dueDate": "2021-03-16T17:00:00.000+00:00",
                                "maturityDate": "2031-03-16T17:00:00.000+00:00",
                                "interestRate": 0.0725,
                                "isSyariah" : false
                            }
                        ]
                    },
                    {
                        "code": "KII",
                        "title": "KII",
                        "image" : "https://byonimage.blob.core.windows.net/dashboard/ki.png",
                        "totals": [
                            {
                                "accountCcy": "IDR",
                                "balance": 6051558.00,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            },
                            {
                                "accountCcy": "USD",
                                "balance": 0,
                                "accountCcyNameID": "Dolar Amerika",
                                "accountCcyNameEN": "US Dollar"
                            }
                        ],
                        "accounts": [
                            {
                                "productCode": "KII-XXXX",
                                "productName": "Product KII",
                                "accountId": "BFCC4759E901721FE053612810AC8FB4",
                                "accountNo": "545830219972",
                                "accountType": "L",
                                "branchCode": "02545",
                                "cif": "0000000000001103277",
                                "accountCcy": "IDR",
                                "balance": 0,
                                "availableBalance": 6051558,
                                "holdBalance" : 187500000,
                                "overdraftBalance": 133931460,
                                "monthlyPayment": 10000000,
                                "dueDate": "2021-03-16T17:00:00.000+00:00",
                                "maturityDate": "2031-03-16T17:00:00.000+00:00",
                                "interestRate": 0.0725,
                                "isSyariah" : false
                            }
                        ]
                    },
                    {
                        "code": "IBL",
                        "title": "IBL",
                        "image" : "https://byonimage.blob.core.windows.net/dashboard/ibl.png",
                        "totals": [
                            {
                                "accountCcy": "IDR",
                                "balance": 751558.00,
                                "accountCcyNameID": "Rupiah Indonesia",
                                "accountCcyNameEN": "Indonesian Rupiah"
                            },
                            {
                                "accountCcy": "USD",
                                "balance": 0,
                                "accountCcyNameID": "Dolar Amerika",
                                "accountCcyNameEN": "US Dollar"
                            }
                        ],
                        "accounts": [
                            {
                                "productCode": "IBL-XXXX",
                                "productName": "Product IBL",
                                "accountId": "BFCC4759E901721FE053612810AC8FB4",
                                "accountNo": "545830219972",
                                "accountType": "L",
                                "branchCode": "02545",
                                "cif": "0000000000001103277",
                                "accountCcy": "IDR",
                                "balance": 0,
                                "availableBalance": 751558,
                                "holdBalance" : 187500000,
                                "overdraftBalance": 133931460,
                                "monthlyPayment": 10000000,
                                "dueDate": "2021-03-16T17:00:00.000+00:00",
                                "maturityDate": "2031-03-16T17:00:00.000+00:00",
                                "interestRate": 0.0725,
                                "isSyariah" : false
                            }
                        ]
                    }
                ]
            },
            "response_code": "00000"
        }
