
## Dashboard: Inquiry Task List [/dashboard/task-list]

### Inquiry Task List [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "taskBO": true,
                "taskKYC": false,
                "isBranchVerification": false,
                "taskFirstDeposit": false,
                "taskCardActivate": false,
                "taskPVB": true,
                "referenceNumber": "1234567890abc",
                "fullName": "cu pat kai",
                "taskBOStatus": "Skip",
                "isBoKtp": true,
                "isBoPassport": false,
                "isComplete": false
            }
        }
