
## Payment Group [/dashboard/point/seru]

### Promo Banner [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "available": 0,
                "accrued": 0,
                "redeemed": 0,
                "expired": 0,
                "url": "http://10.255.7.191:8183/#!/sso?data=bWOFLfiBdNvtzTiHIMVaLkNsYKONFd2JwOCOYGhXCpHTQKVcURkus71pbf2T9QFVlObVYmkYKyua4AchgNZ8WERhd1uXUn2D20Nq1dntxHfXLwl6TIroY0GrOX+yvvsGhzfHOqbF/b4m7t/qxC0ZTf5zDDqxfj8t8sNFhuC5QGAe2zFav5vrGMaM6H+Egc/37R2CpSjePFkwYv8PIlxo6iRM9KUy/vynyIu/Q/qOvJUTiiaDsa5srYPkVC+RL3a90KzsDv8arwYafJNm1LF12alExKjfRl1Bi+3Fq1zz75x7GVlUmd6fjjSSOu4wUiqGaMJNG+Os8dBR21ZBBo4rDQ=="
            }
        }


