
## Dashboard: Saving Multi Currency [/dashboard/saving/multi-currency]

### Saving Multi Currency [POST]

+ Request (application/json)

        {
            "branchCode": "01010",
            "accountType": "S",
            "accountNo": "330810001868",
            "accountCcy": "IDR",
        }

+ Response 200 (application/json)

        {
            "responseDescription": "SUKSES",
            "responseTitle": "",
            "language": "IN",
            "data": {
                "productCode": "TBSMCY9901",
                "productName": "Tanda360Plus-S",
                "accountCcy": "IDR",
                "accountNo": "693810050866",
                "balance": 290579,
                "availableBalance": 190579,
                "holdBalance": 0,
                "overdraftBalance": 0,
                "outstandingUnit": 0,
                "accountType": "S",
                "branchCode": "99693",
                "accountId": "BB72A47705222766E050A8C094073956",
                "cif": "0000000000001680074"
            },
            "response_code": "00000"
        }
