
## Telegraphic Countries [/telegraphic/countries]

### Telegraphic Countries [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "countries": [
                    {
                        "code": "001",
                        "value": "Afghanistan"
                    },
                    {
                        "code": "002",
                        "value": "Albania"
                    },
                    {
                        "code": "003",
                        "value": "Algeria"
                    },
                    {
                        "code": "004",
                        "value": "Andorra"
                    }
                ]
            }
        }
