
## Initial Beneficiary Info [/telegraphic/initial-beneficiary-info]

### Initial Beneficiary Info [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUKSES",
            "data": {
                "category": {
                    "code": "A0",
                    "value": "Perorangan",
                    "description": ""
                },
                "affiliationStatus": {
                    "code": "001",
                    "value": "Warga Negara",
                    "description": ""
                }
            }
        }
