
## Feedback List [/etc/feedback-list]

### Feedback List [GET]

+ Response 200 (application/json)

        {
            "response_code": "00000",
            "response_desc_en": "SUCCESS",
            "response_desc_id": "SUCCESS",
            "data": {
                "listFeedbackCategories": [{
                    "categoryID": "6A8F95D31C39A1DDE050A8C0940738E0",
                    "categoryName": "Keluhan"
                }, {
                    "categoryID": "6A8F95D31C3AA1DDE050A8C0940738E0",
                    "categoryName": "Saran"
                }, {
                    "categoryID": "6A8F95D31C3BA1DDE050A8C0940738E0",
                    "categoryName": "Pertanyaan"
                }]
            }
        }
